/* Per-technique choreography effects. Cosmetic only: no timers change game state. */
globalThis.MURIM_VFX=(()=>{
 const hash=s=>{let n=2166136261;for(const c of s)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0};
 const family=name=>/snow|winter|frost|white silence|cold/i.test(name)?'frost':/black|eclipse|heavenless|shadow|demon|void/i.test(name)?'shadow':/verdant|jade|lotus|petal|spring/i.test(name)?'lotus':/iron|furnace|mountain|stone|earth|palm pressure/i.test(name)?'earth':/breath|dantian|meridian sweep|cycle|reverse/i.test(name)?'breath':/step|footwork|withdrawal|feint/i.test(name)?'step':'cloud';
 const colors={frost:['#a9e5ff','#e9ffff'],shadow:['#b971ec','#ffe7ff'],lotus:['#75e8bb','#f9e0ff'],earth:['#efac59','#fff0c1'],breath:['#7ae0cf','#e4ffff'],step:['#8faec7','#e0f4ff'],cloud:['#88cfff','#f1fcff']};
 function describe(fx={}){const name=fx.technique||fx.affinity||fx.move||'Focused Qi Burst',f=family(name),seed=hash(name),motion=MURIM_MOTION[name]||MURIM_MOTION['Focused Qi Burst'];return {name,family:f,seed,path:motion?.path||'M65 180 Q200 30 330 150',colors:colors[f],rays:7+seed%6,turn:(seed%7-3)*5};}
 function render(fx,opts={}){if(!fx)return '';const d=describe(fx),id='vfx-'+d.seed,stage=Math.min(3,Math.max(0,opts.stage||0)),paths=opts.paths||[],response=fx.response||((fx.enemyDamage||0)>0?'hit':'miss'),guard=['block','parry'].includes(response),miss=['miss','dodge'].includes(response),mode=opts.motion||'full',duration=mode==='fast'?280:mode==='reduced'?40:1080;
 if(['defend','breath','focus'].includes(fx.move)){
  const guard=fx.move==='defend',footwork=fx.move==='focus';
  return '<div class="murimVfx support-vfx family-'+d.family+'" data-technique="'+d.name.replace(/[&<>"]/g,'')+'" data-family="'+d.family+'" data-stage="'+stage+'" style="--vfx:'+d.colors[0]+';--vfx-core:'+d.colors[1]+';--vfx-ms:'+duration+'ms" aria-hidden="true"><svg viewBox="0 0 400 280"><g class="vfxReturn">'+(guard?'<path d="M96 105 Q140 125 184 105 L179 179 Q160 210 140 221 Q113 205 99 179Z"/><ellipse cx="140" cy="163" rx="58" ry="74"/>':footwork?'<path d="M35 220 Q108 178 190 224 M49 234 Q122 192 204 238"/><ellipse cx="115" cy="224" rx="70" ry="15"/>':'<ellipse cx="140" cy="168" rx="60" ry="44"/><ellipse cx="140" cy="168" rx="43" ry="70"/><circle cx="140" cy="168" r="19"/>')+'</g></svg></div>';
 }
 const rays=Array.from({length:d.rays+stage*2},(_,i)=>{const angle=i*2.399+d.seed%6,radius=28+(i*17%44),x=Math.cos(angle)*radius,y=Math.sin(angle)*radius;return `<path class="impactRay" d="M0 0 L${x.toFixed(1)} ${y.toFixed(1)}" style="--ray-delay:${i%3*12}ms"/>`}).join('');
 let motif='';for(let i=0;i<7+stage;i++){const x=95+i*29,y=85+(i*31+d.seed)%115,rotate=(i*43+d.seed)%180;if(d.family==='frost')motif+=`<path class="vfxShard" d="M${x} ${y-19} l6 17 -6 15 -6 -15Z" style="--drift:${20+i*6}px;--delay:${i*18}ms"/>`;else if(d.family==='lotus')motif+=`<path class="vfxPetal" d="M${x} ${y} q-15 -21 0 -30 q19 16 0 30Z" transform="rotate(${rotate} ${x} ${y})" style="--delay:${i*23}ms"/>`;else if(d.family==='earth')motif+=`<path class="vfxRock" d="M${x} 220 l-9 -14 5 -10 17 6 3 16Z" style="--delay:${i*19}ms;--drift:${-15-i*4}px"/>`;else if(d.family==='shadow')motif+=`<path class="vfxEcho" d="${d.path}" transform="translate(${-i*8} ${i*3})" style="--delay:${i*17}ms;opacity:${(.45-i*.04).toFixed(2)}" pathLength="1"/>`;else motif+=`<path class="vfxWind" d="M${x-25} ${y} q25 -13 53 -4" style="--delay:${i*21}ms" pathLength="1"/>`;}
 const second=stage||paths.includes('control')?`<path class="vfxSecond" d="${d.path}" transform="rotate(${d.turn||12} 205 145)" pathLength="1"/>`:'';
 const wave=d.family==='breath'||paths.includes('flowing')?'<g class="vfxReturn"><ellipse cx="135" cy="172" rx="72" ry="38"/><ellipse cx="135" cy="172" rx="48" ry="70"/></g>':'';
 return `<div class="murimVfx family-${d.family} result-${response} ${paths.map(x=>'refinement-'+x).join(' ')}" data-technique="${d.name.replace(/[&<>\"]/g,'')}" data-family="${d.family}" data-stage="${stage}" style="--vfx:${guard?'#b3dce5':d.colors[0]};--vfx-core:${d.colors[1]};--vfx-ms:${duration}ms" aria-hidden="true"><svg viewBox="0 0 400 280" preserveAspectRatio="none"><defs><filter id="${id}"><feGaussianBlur stdDeviation="3"/></filter></defs><g class="vfxCharge"><circle cx="112" cy="165" r="25"/><circle cx="112" cy="165" r="33"/></g><g class="vfxMotif">${motif}</g><path class="vfxGlow" d="${d.path}" filter="url(#${id})" pathLength="1"/><path class="vfxBlade" d="${d.path}" pathLength="1"/><path class="vfxCore" d="${d.path}" pathLength="1"/>${second}${wave}${miss?'':`<g transform="translate(303 157)"><g class="vfxImpact"><circle r="${guard?34:18+stage*6}"/><circle class="outerRing" r="${guard?45:34+stage*8}"/>${guard?'<path d="M-17 -29L21 30M-25 17L28 -20"/>':rays}</g></g>`}</svg></div>`;
 }
 return {family,describe,render};
})();
