window.MURIM_DATA = {
fates:{
"Race":[["Human","Common","Adaptable meridians; varied systems grow efficiently."],["Spirit-Blooded","Rare","Sensitive to ambient qi and spiritual phenomena."],["Demonkin","Epic","Powerful recovery and killing-intent resistance; orthodox suspicion."],["Azure Dragonkin","Legendary","Dragon marrow strengthens body, qi and presence."],["Celestial Descendant","Mythic","Sensitive to heavenly laws and tribulations."],["Primordial Chaosborn","Transcendent","Incompatible energies may coexist within you."]],
"Ability":[["Perfect Meridians","Rare","Open channels grant efficient circulation."],["Sword Heart","Epic","Sword principles arrive as intuition rather than imitation."],["Heavenly Demon Physique","Legendary","Body and cultivation reinforce one another."],["Ten Thousand Arts","Mythic","Techniques break apart into principles you can recombine."],["Divine Formation Mind","Legendary","Patterns in terrain and qi reveal themselves."],["Limitless Evolution","Transcendent","Survived hardship leaves permanent adaptation."]],
"Origin":[["Nameless Village","Common","No lineage protects or defines you."],["Fallen Clan","Rare","A ruined name leaves debts and buried enemies."],["Sect Orphan","Uncommon","Raised beneath sect rules and rivalries."],["Black Market Fighter","Epic","You learned survival where mercy was expensive."],["Hidden Ancient Clan","Legendary","Old blood carries old obligations."],["Reincarnated Supreme Master","Mythic","Fragments of another lifetime haunt your instincts."]],
"Affinity":[["Flame Yang","Uncommon","Hot, forceful qi."],["Glacial Yin","Rare","Cold, precise qi."],["Heavenly Lightning","Epic","Violent qi with breakthrough affinity."],["Venomous Wood","Epic","Life and poison share one root."],["Void","Mythic","Absence itself answers your circulation."],["Primordial Chaos","Transcendent","Qi before division into ordinary principles."]],
"Unique Power":[["Eye of Truth","Rare","See circulation, disguises, injuries and formation flaws."],["Martial Devourer","Legendary","Take essence from defeated beings at a corruption risk."],["Heavenly Archive","Mythic","Perfectly retain and compare martial knowledge."],["Nine-Breath Reversal","Legendary","Revert your own condition roughly nine breaths at great soul strain."],["Karmic Sovereign","Mythic","Perceive gratitude, hatred, danger and obligation."],["Infinite Assimilation","Transcendent","Assimilate traits at escalating risk."]]
},
npcs:{
han:{gender:"Male",appearance:{body:"male",face:2,hair:1,palette:5},name:"Han Muyeon",role:"Cloudveil Sect Master",realm:"Profound",location:"Cloudveil Sect",goal:"Keep Cloudveil stable while discovering why Black Lotus moved openly.",mood:"Guarded"},
seo:{gender:"Female",appearance:{body:"female",face:2,hair:2,palette:4},name:"Seo Hwarin",role:"Frost Sword Saint",realm:"Life-and-Death",location:"Frostblade Peak",goal:"Find a disciple who understands sword intent instead of copying forms.",mood:"Distant"},
mu:{gender:"Male",appearance:{body:"male",face:3,hair:3,palette:1},name:"Mu Cheon",role:"Black Heaven Emissary",realm:"Profound",location:"Cloudveil Sect",goal:"Decide whether the five-card prodigy is useful, dangerous, or entertaining.",mood:"Amused"},
jin:{gender:"Female",appearance:{body:"female",face:1,hair:2,palette:0},name:"Jin Seol",role:"Unaffiliated Investigator",realm:"First-Rate",location:"Jade River City",goal:"Discover what happened to the previous Vessels and the missing survivor.",mood:"Suspicious"},
tang:{gender:"Female",appearance:{body:"female",face:3,hair:1,palette:2},name:"Tang Yerin",role:"Hundred Herb Physician",realm:"Second-Rate",location:"Jade River City",goal:"Build a medical practice without becoming property of a major faction.",mood:"Busy"},
gwak:{gender:"Male",appearance:{body:"male",face:3,hair:2,palette:3},name:"Gwak Il",role:"Beggar Network Informant",realm:"Second-Rate",location:"Jade River City",goal:"Sell information without becoming the most interesting man in the room.",mood:"Curious"},
baek:{gender:"Male",appearance:{body:"male",face:2,hair:1,palette:1},name:"Baek Dojin",role:"Iron Palm Disciple",realm:"First-Rate",location:"Jade River City",goal:"Prove his strength publicly and find rivals worth remembering.",mood:"Proud"},
hwang:{gender:"Male",appearance:{body:"male",face:2,hair:3,palette:3},name:"Hwang Geon",role:"Master Blacksmith",realm:"Third-Rate",location:"Ten Thousand Lantern Market",goal:"Forge a weapon whose name survives longer than its owner.",mood:"Gruff"},
lin:{gender:"Female",appearance:{body:"female",face:1,hair:3,palette:5},name:"Lin Yue",role:"Spirit-Clothier",realm:"Mortal",location:"Jade River City",goal:"Recover the lost methods of spirit-thread tailoring without selling them to a faction.",mood:"Sharp-eyed"}
},
locations:["Awakening Hall","Cloudveil Sect","Frostblade Peak","Jade River City","Crane & Reed Martial Inn","Ten Thousand Lantern Market","Red Moon Ruins","Hundred Herb Valley","Black Heaven Palace"],
factions:["Orthodox Alliance","Black Heaven Palace","Imperial Martial Bureau","Ten Thousand Merchant Pavilion","Beggar Network","Hundred Herb Valley","Black Lotus Society"]
};