/* Directed actions never inherit a bystander as their target. */
(function(root){'use strict';
 const archetypes={bandit:{role:'Road Bandit',terms:['bandit','brigand','outlaw'],goal:'Find a way out of a dangerous trade before a stronger gang claims the road.',difficulty:9,palettes:[0,3,6]},vagabond:{role:'Wandering Vagabond',terms:['vagabond','wanderer','ronin'],goal:'Find shelter and a road worth following.',difficulty:7,palettes:[1,3,7]},student:{role:'Martial Student',terms:['student','disciple','apprentice'],goal:'Test a developing method without bringing shame to a teacher.',difficulty:8,palettes:[1,4,5]},guard:{role:'Road Guard',terms:['guard','sentry','watchman'],goal:'Keep the passage orderly and travelers safe.',difficulty:10,palettes:[3,5,7]},merchant:{role:'Traveling Merchant',terms:['merchant','trader','peddler'],goal:'Deliver a modest cargo and return home with a fair profit.',difficulty:5,palettes:[2,4,7]},traveler:{role:'Passing Traveler',terms:['traveler','traveller','stranger'],goal:'Learn whether the next road is safe before nightfall.',difficulty:6,palettes:[1,2,3]}};
 const surnames=['Ryu','Chae','Yun','Kang','Min','Jang','Hong','Nam','Park','Im','Noh','Jeong','Son','Bae','Suh','Kwon'],given={male:['Taewon','Seojun','Dohyun','Haejin','Jiwon','Youngsu','Sangho','Jungho','Taemin','Seungil','Haneul','Minsu'],female:['Yuna','Seorin','Haeun','Jiwon','Chaerin','Minseo','Nari','Sora','Daeun','Ara','Yeona','Sehwa']};
 const hash=s=>{let n=2166136261;for(const c of String(s))n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0},quote=s=>String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),has=(s,w)=>new RegExp('(?:^|\\W)'+quote(w)+'(?:$|\\W)','i').test(s),clean=s=>String(s??'').trim().slice(0,1200);
 function ensure(S){if(!S.world.encounters||typeof S.world.encounters!=='object'||Array.isArray(S.world.encounters))S.world.encounters={serial:0,records:[]};const e=S.world.encounters;e.serial=Math.max(0,Math.min(1e9,Math.floor(Number(e.serial)||0)));const seen=new Set();e.records=Array.isArray(e.records)?e.records.filter(r=>r&&/^enc-[a-z0-9-]+$/.test(r.id)&&archetypes[r.archetype]&&!seen.has(r.id)&&seen.add(r.id)).slice(-24):[];for(const n of e.records){n.name=clean(n.name).slice(0,80)||'Unnamed Traveler';n.role=archetypes[n.archetype].role;n.goal=archetypes[n.archetype].goal;n.memory=Array.isArray(n.memory)?n.memory.filter(x=>typeof x==='string').slice(0,8).map(x=>x.slice(0,300)):[];for(const k of ['trust','bond','respect','grudge','fear','encounters','victories','defeats'])n[k]=Math.max(k==='trust'?-100:0,Math.min(k==='encounters'?999:100,Math.floor(Number(n[k])||0)));n.difficulty=Math.max(4,Math.min(30,Math.floor(Number(n.difficulty)||archetypes[n.archetype].difficulty)));e.serial=Math.max(e.serial,parseInt(n.id.split('-').at(-1),36)||0);}return e}
 function get(S,id){return S.npcs?.[id]||S.world.encounters?.records?.find(n=>n.id===id)||null}
 function active(S){const id=S.conversation?.npc,n=get(S,id);return S.scene?.conversation&&id===S.scene?.npc&&n?.location===S.world.location?id:null}
 function all(S){return [...Object.entries(S.npcs||{}).map(([id,n])=>({...n,id,main:true})),...(S.world.encounters?.records||[]).map(n=>({...n,main:false}))]}
 function focus(text,intent){let q=clean(text).replace(/^\s*(?:and\s+)?(?:i\s+)?(?:try to\s+|attempt to\s+|want to\s+)?/i,'');if(intent==='speak'){const m=q.match(/^(?:tell|ask|greet|thank|insult|threaten|persuade|convince)\s+(.+?)(?:\s+(?:that|about|whether|why|how|to)\b|[,.:“"!?]|$)/i)||q.match(/^(?:say|talk|speak|whisper|shout|apologize|apologise)\s+(?:to|with)\s+(.+?)(?:\s+about\b|[,.:“"!?]|$)/i)||q.match(/^(?:hello|hi|greetings)[, ]+(.+?)[.!?]?$/i);return m?{value:m[1],explicit:true}:{value:q.replace(/[“"][\s\S]*$/,''),explicit:false}}
  if(intent==='gift'){const to=q.match(/\bto\s+(.+?)[.!?]?$/i);if(to)return {value:to[1],explicit:true};q=q.replace(/^(?:give|gift|offer)\s+/i,'');return {value:q,explicit:true}}
  q=q.replace(/^(?:go\s+(?:and\s+|to\s+)?)?(?:attack|strike|fight|punch|slash|challenge|duel|spar(?:\s+with)?|help|assist|protect|rescue|support|shield|save|treat|heal|bandage|tend|diagnose)\s*/i,'');return {value:q,explicit:!!q};
 }
 function resolve(S,text,intent,{allowGeneric=true}={}){
  const f=focus(text,intent),q=f.value.toLowerCase().split(/\s+(?:not|rather than|instead of|near|beside|next to|before|after|while|who|that|protecting|guarding|threatening|attacking|from)\s+/)[0].replace(/[,;]\s*$/,''),people=all(S),here=people.filter(n=>n.location===S.world.location),current=active(S),fail=message=>({ok:false,clarification:message});
  if(intent==='treat'&&/\b(?:myself|my (?:wound|injur|body)\w*|self)\b/i.test(q))return {ok:true,type:'self',id:null};
  let matches=people.filter(n=>has(q,n.name));
  // Full names outrank first-name aliases; unique aliases still work when the person is elsewhere.
  if(!matches.length)matches=people.filter(n=>has(q,n.id)||n.name.split(' ').filter(w=>w.length>=3).some(w=>has(q,w)));
  if(matches.some(n=>[n.name,n.id,...n.name.split(' ').filter(w=>w.length>=3)].some(alias=>new RegExp('(?:^|\\W)'+quote(alias)+"['’]s\\s",'i').test(q))))return fail('That names someone associated with a person, not necessarily that person. Name the intended individual or a generic role; their affiliation has not been established.');
  if(matches.length&&/\b(?:and|or)\b/.test(q)&&Object.values(archetypes).some(r=>r.terms.some(t=>has(q,t))))return fail('A named person and another kind of person are both mentioned. Choose one intended target.');
  if(matches.length>1)return fail('More than one person is named. Which single person should this action address?');
  if(matches.length===1){const n=matches[0];if(n.location!==S.world.location)return fail(`${n.name} is at ${n.location}. Find them there before directing this action at them.`);if(intent==='attack'&&!n.main&&n.status==='recovering')return fail(`${n.name} is still recovering from the last exchange and cannot offer another fair fight. Seek a different opponent.`);return {ok:true,type:n.main?'main':'encounter',id:n.id,explicit:true};}
  const roles=Object.entries(archetypes).filter(([,r])=>r.terms.some(t=>has(q,t)));
  if(roles.length>1)return fail('Several kinds of person are named. Choose one intended target.');
  if(roles.length===1&&allowGeneric){const [archetype]=roles[0];const record=here.find(n=>!n.main&&n.archetype===archetype&&n.id===current);return record&&intent!=='attack'?{ok:true,type:'encounter',id:record.id,explicit:true}:{ok:true,type:'new',archetype,explicit:true};}
  if(/\b(?:him|her|them|he|she|you)\b/.test(q)){if(!current)return fail('That pronoun has no clear current addressee. Name the person you mean.');const n=get(S,current);if(/\b(?:him|he)\b/.test(q)&&n.gender==='Female'||/\b(?:her|she)\b/.test(q)&&n.gender==='Male')return fail('That pronoun does not match the current addressee. Name the person you mean.');return {ok:true,type:S.npcs[current]?'main':'encounter',id:current};}
  if(intent==='speak'&&!f.explicit&&current)return {ok:true,type:S.npcs[current]?'main':'encounter',id:current};
  if(intent==='assist'&&!f.explicit&&current)return {ok:true,type:S.npcs[current]?'main':'encounter',id:current};
  if(intent==='treat'&&!f.explicit)return {ok:true,type:'self',id:null};
  return fail(f.explicit?'Name the intended person or a clear role such as bandit, vagabond, student, guard, merchant, or traveler. Nobody nearby has been substituted.':'Name the person this action should address. Being nearby does not make someone its target.');
 }
 function create(S,archetype){const cfg=archetypes[archetype];if(!cfg)throw Error('Unknown encounter archetype');const e=ensure(S),serial=++e.serial,seed=hash(`${S.seed}|encounter|${serial}|${archetype}`),gender=seed%2?'Female':'Male',body=gender.toLowerCase();let name=surnames[seed%surnames.length]+' '+given[body][Math.floor(seed/16)%given[body].length];if(all(S).some(n=>n.name===name))name+=' '+String(serial);const n={id:`enc-${archetype}-${serial.toString(36)}`,name,role:cfg.role,archetype,gender,appearance:{body,face:Math.floor(seed/5)%3+1,hair:Math.floor(seed/17)%6+1,palette:cfg.palettes[Math.floor(seed/29)%cfg.palettes.length],expression:'neutral'},location:S.world.location,goal:cfg.goal,difficulty:cfg.difficulty+Math.min(15,Math.max(0,S.player.realm||0)*2),trust:0,bond:0,respect:0,grudge:0,fear:0,memory:[],metDay:S.world.day,lastDay:S.world.day,encounters:0,defeats:0,victories:0,status:'present'};e.records.push(n);e.records=e.records.slice(-24);return n}
 function remember(S,n,text){n.lastDay=S.world.day;n.memory.unshift(clean(text).slice(0,300));n.memory=n.memory.slice(0,8);n.relationshipStatus=n.grudge>=4?'Rival':n.bond>=5&&n.trust>=3?'Friend':n.trust<=-4?'Wary':'Acquaintance';}
 function interact(S,n,text,kind='speak'){const q=text.toLowerCase();let out;if(kind==='assist')return {text:`${n.name} explains their immediate concern: ${n.goal} Name a concrete step before any help or reward is recorded.`,occurred:false};
  const repeat=n.memory.some(m=>m===clean(text).slice(0,300));if(/\b(?:insult|threaten|idiot|fool|coward|kill you|hurt you|destroy you)\b/.test(q)){if(!repeat){n.trust=Math.max(-100,n.trust-2);n.grudge=Math.min(100,n.grudge+2);}out=`${n.name} draws back. “Speak with care. I am not obliged to take that from you.” They remember the insult; no attack has occurred.`;}else if(/sorry|apologi/.test(q)){if(!repeat&&n.grudge>0){n.grudge--;n.trust++;}out=`${n.name} hears the apology. “Let your next action show what those words mean.”`;}else if(/\b(?:i promise|i swear|i give you my word)\b/.test(q)){S.world.narrative??={};S.world.narrative.promises??=[];if(!repeat){S.world.narrative.promises.push({id:`promise-${n.id}-${S.actionNo+1}`,npc:n.id,text:clean(text).slice(0,260),status:'open',day:S.world.day,source:'player-explicit-promise'});S.world.narrative.promises=S.world.narrative.promises.slice(-32);}out=`${n.name} listens carefully. “Then I will remember what you said.” The promise remains open; speaking it has not fulfilled it.`;}else if(/promise|word|owe/.test(q)&&(S.world.narrative?.promises||[]).some(p=>p.npc===n.id&&p.status==='open')){const p=S.world.narrative.promises.filter(p=>p.npc===n.id&&p.status==='open').at(-1);out=`${n.name} remembers your promise: “${p.text}” It remains unresolved.`;}else if(/goal|want|plan|hope/.test(q))out=`${n.name} answers plainly: “${n.goal}”`;else out=`${n.name} gives you ${n.grudge?'a guarded':'an attentive'} look. “I have time for a few words.” ${n.goal}`;remember(S,n,text);S.actionNo++;return {text:out,occurred:true};}
 function finish(S,c,won){const n=c?.encounter&&get(S,c.encounter.id);if(!n||c.encounterResolved)return;c.encounterResolved=true;n.encounters++;if(won===true)n.defeats++;if(won===false)n.victories++;n.status=won===true?'recovering':won===false?'victorious':'present';remember(S,n,`${S.player.name} ${won===true?'won':won===false?'lost':'withdrew from'} our encounter on day ${S.world.day}.`)}
 // Wardrobe is presentation, not loot or an implicit equipment stat grant.
 // Derive it from the saved identity so old encounters receive stable defaults.
 const wardrobes={bandit:{outfits:['scout','robe'],heads:['shadow-assassin-mask','']},vagabond:{outfits:['robe','scout'],heads:['reed-travel-hat','']},student:{outfits:['robe'],heads:['cloudveil-circlet','']},guard:{outfits:['lamellar'],heads:['lamellar-helm']},merchant:{outfits:['ceremonial','robe'],heads:['scholar-hairpin','']},traveler:{outfits:['scout','robe'],heads:['reed-travel-hat','']}};
 function visual(n){
  const kit=wardrobes[n?.archetype];if(!kit||!n?.id)return null;
  const seed=hash(n.id+'|wardrobe');
  return {outfit:kit.outfits[seed%kit.outfits.length],head:kit.heads[Math.floor(seed/7)%kit.heads.length],palette:Number.isInteger(n.appearance?.palette)?n.appearance.palette:0};
 }
 const api={archetypes,ensure,get,active,resolve,create,interact,remember,finish,visual};root.MURIM_ENCOUNTERS=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
