/* Optional display-only artwork. Local encounter art remains the default. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MURIM_ENCOUNTER_ART=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
 'use strict';
 const VERSION=1,ROLES=['bandit','vagabond','student','guard','merchant','traveler'],inflight=new Map();
 const object=x=>x&&typeof x==='object'&&!Array.isArray(x),keys=(x,list)=>object(x)&&Object.keys(x).every(k=>list.includes(k));
 function safeUrl(value){return typeof value==='string'&&/^\/api\/encounter-art\/cache\/[a-f0-9]{64}\.png$/.test(value)?value:null;}
 function validateReceipt(value){
  if(!keys(value,['schema','id','source','encounter'])||value.schema!==VERSION||typeof value.id!=='string'||!/^encounter-art:[a-f0-9]{1,16}:enc-[a-z]+-[a-z0-9]+$/.test(value.id))throw Error('A settled incidental encounter is required.');
  const n=value.encounter,s=value.source,a=n?.appearance;
  if(!keys(n,['id','name','archetype','appearance'])||!ROLES.includes(n.archetype)||!new RegExp('^enc-'+n.archetype+'-[a-z0-9]+$').test(n.id)||!value.id.endsWith(':'+n.id)||typeof n.name!=='string'||!n.name.trim()||n.name.length>80||/[\x00-\x1f<>]/.test(n.name))throw Error('The encounter identity is invalid.');
  if(!keys(s,['kind','worldSeed','metDay'])||s.kind!=='world-encounter'||!Number.isSafeInteger(s.worldSeed)||s.worldSeed<0||!Number.isSafeInteger(s.metDay)||s.metDay<1||s.metDay>1000000||value.id!==`encounter-art:${s.worldSeed.toString(16)}:${n.id}`)throw Error('The encounter provenance is invalid.');
  if(!keys(a,['body','face','hair','palette'])||!['male','female'].includes(a.body)||!Number.isInteger(a.face)||a.face<1||a.face>3||!Number.isInteger(a.hair)||a.hair<1||a.hair>6||!Number.isInteger(a.palette)||a.palette<0||a.palette>7)throw Error('The encounter appearance is invalid.');
  return Object.freeze({schema:VERSION,id:value.id,source:Object.freeze({...s}),encounter:Object.freeze({id:n.id,name:n.name,archetype:n.archetype,appearance:Object.freeze({...a})})});
 }
 function fromState(state,id){
  const n=state?.world?.encounters?.records?.find(x=>x.id===id);if(!n||state.npcs?.[id])throw Error('Generated encounter art is available only for an established incidental character.');
  const seed=Number(state.seed);return validateReceipt({schema:VERSION,id:`encounter-art:${seed.toString(16)}:${n.id}`,source:{kind:'world-encounter',worldSeed:seed,metDay:n.metDay},encounter:{id:n.id,name:n.name,archetype:n.archetype,appearance:{body:n.appearance?.body,face:n.appearance?.face,hair:n.appearance?.hair,palette:n.appearance?.palette}}});
 }
 async function readJson(response,maximum=12000){if(!response.body?.getReader){const value=await response.text();if(value.length>maximum)throw Error('The artwork response exceeded its limit.');return JSON.parse(value);}const reader=response.body.getReader(),decoder=new TextDecoder();let content='',bytes=0;try{for(;;){const part=await reader.read();if(part.done)break;bytes+=part.value.byteLength;if(bytes>maximum)throw Error('The artwork response exceeded its limit.');content+=decoder.decode(part.value,{stream:true});}return JSON.parse(content+decoder.decode());}finally{await reader.cancel().catch(()=>{});}}
 async function boundedFetch(url,init,options,timeout){const control=new AbortController(),parent=options.signal,abort=()=>control.abort(parent?.reason);if(parent?.aborted)abort();else parent?.addEventListener('abort',abort,{once:true});const timer=setTimeout(()=>control.abort('timeout'),timeout);try{if(control.signal.aborted)throw Error('Cancelled');const response=await(options.fetch||fetch)(url,{...init,credentials:'same-origin',redirect:'error',signal:control.signal});let data;try{data=await readJson(response);}catch{throw Object.assign(Error('The optional artwork server is unavailable or returned an unsupported response. Local artwork remains active.'),{code:'ART_UNAVAILABLE'});}if(!response.ok)throw Object.assign(Error(data.message||'Optional encounter artwork is unavailable. Local art remains in use.'),{code:data.code||'ART_UNAVAILABLE'});return data;}catch(error){if(control.signal.aborted)throw Object.assign(Error('Artwork generation was interrupted. Local art remains in use; a dispatched reservation is retained.'),{code:parent?.aborted?'CANCELLED':'TIMEOUT'});if(!error.code)throw Object.assign(Error('The optional artwork server could not be reached. Local artwork remains active.'),{code:'ART_UNAVAILABLE'});throw error;}finally{clearTimeout(timer);parent?.removeEventListener('abort',abort);}}
 async function status(options={}){return boundedFetch('/api/encounter-art/status',{method:'GET'},options,5000);}
 async function request(receipt,options={}){
  if(options.enabled!==true)return {ok:false,code:'ART_DISABLED',message:'Optional generated artwork is off. Local encounter art is active.'};
  let checked;try{checked=validateReceipt(receipt);}catch(error){return {ok:false,code:'INVALID_ART_RECEIPT',message:error.message};}
  if(inflight.has(checked.id))return {ok:false,code:'ALREADY_PENDING',message:'Artwork for this encounter is already being requested.'};
  inflight.set(checked.id,true);try{const value=await boundedFetch('/api/encounter-art',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({receipt:checked,consent:true})},options,105000);
   if(!keys(value,['ok','url','encounterId','receiptId','cacheKey','cacheHit','promptVersion','reservationUsd'])||value.ok!==true||value.receiptId!==checked.id||value.encounterId!==checked.encounter.id||!safeUrl(value.url)||!/^\w{64}$/.test(value.cacheKey)||value.url!==`/api/encounter-art/cache/${value.cacheKey}.png`)throw Error('The artwork service returned an invalid display result.');
   return Object.freeze({...value,url:safeUrl(value.url)});
  }catch(error){return {ok:false,code:error.code||'ART_UNAVAILABLE',message:error.message||'Optional encounter artwork is unavailable. Local art remains in use.'};}finally{inflight.delete(checked.id);}
 }
 function mountPreferences({host,stateGetter,onCommit}){
  if(!host||typeof stateGetter!=='function')throw Error('Artwork settings require a host and state getter.');host.querySelector?.('#encounterArtSettings')?.remove();const doc=host.ownerDocument||document,box=doc.createElement('section');box.id='encounterArtSettings';
  const label=doc.createElement('label'),input=doc.createElement('input'),caption=doc.createElement('span'),info=doc.createElement('p'),check=doc.createElement('button');input.type='checkbox';input.id='encounterArtEnabled';input.checked=stateGetter().preferences?.encounterArtEnabled===true;caption.textContent='Allow optional generated encounter portraits';label.appendChild(input);label.appendChild(caption);info.setAttribute('role','status');info.textContent='Off by default. Each portrait requires its own Generate button; local art remains available. The server image budget defaults to $0.';check.type='button';check.textContent='Check artwork budget';box.appendChild(label);box.appendChild(info);box.appendChild(check);host.appendChild(box);
  input.addEventListener('change',()=>{const s=stateGetter();s.preferences??={};const previous=s.preferences.encounterArtEnabled===true;s.preferences.encounterArtEnabled=input.checked;try{onCommit?.(s);info.textContent=input.checked?'Optional portraits enabled in this save. Generation still requires an explicit click and a configured server budget.':'Generated portraits are off; local encounter artwork is active.';}catch{s.preferences.encounterArtEnabled=previous;input.checked=previous;info.textContent='The artwork preference could not be saved.';}});
  check.addEventListener('click',async()=>{check.disabled=true;info.textContent='Checking the separate artwork budget; no image is requested…';try{const data=await status();info.textContent=`${data.ready?'Artwork service configured.':'Artwork service unavailable or disabled.'} Image budget: $${Number(data.budget?.remainingUsd||0).toFixed(4)} remaining of $${Number(data.budget?.limitUsd||0).toFixed(4)} this ${data.budget?.periodKind||'period'}. No image was requested.`;}catch{info.textContent='The optional artwork server is unavailable. Local encounter art remains fully available.';}finally{check.disabled=false;}});return box;
 }
 return Object.freeze({VERSION,ROLES,safeUrl,validateReceipt,fromState,status,request,mountPreferences});
});
