/* Cookie's guide: factual rules, live catalogues and a bounded reading history. */
globalThis.MURIM_GUIDE=(()=>{
 const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rows=[
 ["start","First steps","Basics","Create a cultivator, choose five fates, then Awaken.","Type what you say or attempt in Story. Suggested choices are shortcuts; inspect the resulting changes, keep talking, or deliberately leave. World is where you choose a destination.","Creation costs nothing. Resolved actions can advance time; four phases make a day. Combat and pending responses limit side activities.","Try “I ask about the missing courier, then inspect the seal.” Your character learns through the parts the game actually resolves.","story,freeform,training"],
 ["creation","Appearance & five fates","Basics","Body Template, face, hair, palette and expression define your saved look.","Use the creator before Awaken. Choose Race, Ability, Origin, Affinity and Unique Power; every category is required. Body Template is the appearance selector.","Appearance is cosmetic. Fates affect starting advantages, access or reactions; Origin also changes location, resources and the opening problem.","Switch hair while checking the preview. A stronger-sounding fate is not protection against injuries or poor resource management.","start,stats"],
 ["stats","Attributes, mastery & resources","Growth","Your martial realm, learned mastery and current condition affect what you can do.","Growth shows your realm and breakthrough requirements. Arts and Life show learned skills as realm tier, mastery out of 10 and progress to the next level.","HP is survival, Qi fuels techniques, and silver buys goods. Skills improve through relevant resolved use. Injuries and fatigue reduce performance; mastery is permanent.","Mastery caps at 10 in each skill tier. HP, relationships, attributes and money do not have that cap.","cultivation,training,mastery"],
 ["time","Time & action restrictions","Basics","Dawn, Noon, Dusk and Night form a day.","Resolve the current response before taking a side activity. The world, NPC intentions and deadlines respond when an action advances time.","Travel, work, combat and recovery can cost time. Asking Cookie, reading text and opening menus give no skill XP.","Reviewing an old reply does not replay its costs or rewards. A request for clarification does not complete your attempted action.","story,quests,freeform"],
 ["story","Scenes, chat & consequences","Story","Typed actions and suggested choices share the same mechanical resolver.","Speak to someone present, examine the surroundings, make a practical attempt, or say that you want to leave. Read the measured outcome before continuing.","Mechanics decide costs and consequences. Narration describes those outcomes; it cannot award unearned power or decide your next voluntary choice.","Ask a follow-up without changing the subject. A conversation stays in its scene until an action or world event justifies moving it.","freeform,relations,narrator"],
 ["freeform","Typing dialogue & actions","Story","Tell the game what you say or try. Offline narration uses local intent rules; connected narration uses a configured service.","You can write speech, an action, or both. Name a character when several people are present. Prefix a rules question with OOC to separate it from in-character speech.","An attempt is validated before costs or rewards. Important ambiguity calls for clarification. Unsupported wording cannot invent items, mastery, victories or new rules.","Try “I tell Jin I found the letter, then compare its seal with the ledger.” The outcome, rather than the wording alone, determines what teaches you.","narrator,story,training"],
 ["combat","Combat tutorial","Combat","Read enemy intent, then choose one exchange.","Strike threatens a heavy counter: defend or use footwork. Guard resists direct attacks: Qi can bypass its accuracy penalty. Recovery is a safer window to breathe or press an attack.","Each accepted action resolves once. Qi is spent when required; HP and momentum change at the exchange. Repeating an approach lets the enemy adapt. Break away leaves combat with fatigue.","Open with defense against a committed strike, then spend momentum on offense. Repeatedly clicking during animation does not grant extra turns.","defense,techniques,recovery"],
 ["defense","Guard, movement & momentum","Combat","Defense and footwork create momentum up to three.","Combat offers Defend, Feint & Thunderstep, and any inherited defensive/movement methods. Enemy intent describes the upcoming exchange.","Defense reduces damage; against a committed strike it can parry. Footwork checks perception/movement and can evade a committed strike. A successful offensive hit spends momentum for more damage.","Build momentum when the enemy is dangerous. Neither defense nor movement is an unconditional invulnerability button.","combat,techniques"],
 ["techniques","Learned techniques & evolving forms","Combat","Every acquired art and technique has mastery 1–10 within its own realm tier.","Unlock a technique through a teacher, manual, quest or discovery. Use it in a meaningful resolved exchange to improve it. Arts shows each known method and whether it can evolve.","No mastery is awarded for selecting a menu, watching an animation, or naming a technique in chat. Costs and learned-method requirements still apply in combat.","A method in the compendium is not automatically learned. A mastered lower-tier method stays useful while you develop another.","training,mastery,transcendence"],
 ["cultivation","Martial realms & breakthroughs","Growth","Martial realm is your overall cultivation tier; skill mastery is a separate track.","Meaningful actions build cultivation insight and foundation. Growth shows the next realm and its insight, foundation, stability and deviation requirements. Choose Breakthrough when ready.","A ready breakthrough has no random failure. It adds maximum HP and Qi, strengthens realm presence, and permits higher-tier skill forms. Foundation drops by 8 and stability by 10.","Rest before advancing if your condition is poor. You do not need to master every skill; unfinished skills keep their existing mastery and XP.","realms,transcendence,recovery"],
 ["training","Learning through meaningful use","Growth","Skills improve through actual use, without mandatory training buttons.","Resolve a sword exchange, evade a threat, investigate a clue, treat an injury, produce an item, or navigate a real journey. Only relevant learned skills receive mastery XP.","Challenge and contribution scale rewards; a meaningful failure can teach less than a success. Repeating the same approach in the same day gives diminishing rewards, then none.","Opening a forge teaches nothing; completing its recipe can teach Smithing. Saying “I master the sword” grants no mastery. Teachers unlock methods instead of filling a practice bar.","mastery,techniques,craft"],
 ["recovery","Rest, medicine & injuries","Growth","Rest and medicine restore condition; injuries can outlast the exchange that caused them.","Use available rest actions and Bag consumables. Inspect injury details in Growth before further exertion.","Medicine consumes an item. Rest advances time. Defeat is survivable but adds injury and fatigue; Nine-Breath Reversal has a Qi cost and causes Soul Strain.","Carry salve before dangerous travel. Healing HP alone may not remove every injury or cultivation problem.","bag,combat,cultivation"],
 ["bag","Inventory & equipment","Life","Bag stores stacks and equips weapons, armor and accessories.","Tap Equip or Unequip beside eligible gear. Consumables expose their own use action. Current bonuses come from the equipped item, quality and familiarity.","Using or crafting consumes quantities. Consuming the final equipped ingredient clears that slot. Unequipped gear gives no equipment bonus.","Check that a crafted weapon is equipped before a duel. Owning a weapon and using it are separate states.","craft,trade,smith"],
 ["craft","Crafting & life skills","Life","Life provides work, gathering and recipes for practical skills.","Read each activity and recipe requirement. Live recipe entries below list the exact definitions. Smithing and Tailoring have location-specific workshops.","Materials, silver, skill and time may be required. Activities increase relevant experience and can influence artisan renown and future jobs.","Gather the listed materials before crafting. A catalogue entry is not permission to craft anywhere without requirements.","smith,clothier,alchemy,jobs"],
 ["smith","Blacksmith","Life","The blacksmith makes and refines gear in Ten Thousand Lantern Market.","Travel there, open Life → Blacksmith, then inspect the enabled recipes or refinement requirements.","Crafting charges recipe costs and consumes ingredients. Refinement improves persistent gear quality. Insufficient materials, skill or money prevent the action.","Forge a Tempered Steel Jian, then equip it in Bag. Remember that using your last equipped sword as an ingredient unequips it.","bag,craft,trade"],
 ["clothier","Clothier & robe dyes","Life","Jade River City provides tailoring and cosmetic robe dyes.","Open Life → Clothier in Jade River City. Select a new palette; the current palette cannot be bought again.","A dye costs 3 silver and persists without changing hair or face. Cosmetic palette changes do not replace the armor item or create stat bonuses.","Pick a new palette, then view Growth. Do not expect a dye to repair armor or increase defense.","bag,craft,creation"],
 ["alchemy","Alchemy & gathering","Life","Alchemy turns listed ingredients into useful consumables.","Use Life recipes and relevant gathering activities. Herbalism and Alchemy are distinct skills.","Recipes have ingredients and skill requirements; crafted quantities persist. A healing consumable must still be used from Bag.","Read the recipe first and gather only what is missing. Avoid consuming your last ingredient before a planned commission.","craft,recovery,jobs"],
 ["trade","Buying, selling & the economy","Life","Prices reflect item value and local economic conditions.","Open the available market/shop from Life. Quantity, currency and location constrain transactions.","Buying spends silver; selling removes inventory. Buy/sell spreads prevent effortless same-shop profit. World supply and trade conditions evolve.","Compare the displayed price with your travel needs. Do not sell the last weapon you rely on before a dangerous road.","bag,world,jobs"],
 ["jobs","Jobs, commissions & renown","Life","Jobs and commissions convert skill, time or goods into rewards.","Inspect available work in Life and local workshop commissions. Requirements are shown before completion.","Materials may be consumed. Crafting reputation can improve social recognition and future opportunities; missing skill or stock blocks completion.","Keep commission materials separate in your planning. Crafting an item does not automatically hand it over to a client.","craft,quests,trade"],
 ["relations","Relationships & NPC memory","People","Trust, respect, bond, affection and grievance influence future behavior.","People shows known characters, their locations and available social actions. Meet local access requirements for in-person interactions.","NPCs remember important exchanges. Help, gifts, shared challenges, betrayal and conflict can coexist in memory; one number does not erase another.","Repair a grievance through relevant actions. High respect alone does not mean friendship or romance.","romance,companions,reputation"],
 ["romance","Romance, promises & commitment","People","Romance grows through eligible relationship actions and circumstances.","Inspect the character’s available bond actions. Romance and commitment are gated by the actual relationship; unavailable options explain missing conditions.","Affection, bond, jealousy and promises can affect outcomes. Gifts and warm dialogue do not guarantee commitment. Broken promises can return as consequences.","Build trust before pressing for intimacy. Do not treat a high affection number as consent or a guaranteed outcome.","relations,companions"],
 ["companions","Companions & shared history","People","An eligible companion travels with you and contributes according to support mode.","Use People to invite or dismiss a companion and choose the available mode.","Relationship requirements apply. Shared travel and combat leave memories and may change bond or respect. A companion is not a second directly controlled combat unit.","Choose support suited to your task. Do not assume every known NPC can be recruited immediately.","relations,combat,travel"],
 ["reputation","Reputation, heat & faction standing","World","Public renown, dangerous attention and faction approval are separate systems.","Inspect Growth, World and faction-related outcomes after public choices.","Victories, methods, promises and forbidden study can change how opportunities and risks develop. Heat can attract attention even when reputation is positive.","Consider witnesses before a forceful solution. Fame does not make hostile factions friendly.","sects,world,story"],
 ["sects","Sects, duties & inheritance","World","Sect membership and learning a lineage are related but separate.","Arts lists teachers, locations, inherited methods and available access. Reputation, realm and discoveries can open a later method.","Hostile factions may refuse instruction. A transmitted method is acquired at mastery 1 in your current realm tier; it improves through use afterward.","Seek an actual inheritance when its requirements are met. Repeatedly requesting the same lesson does not build unlimited mastery.","techniques,reputation,training"],
 ["quests","Threads, quests & deadlines","Story","Authored threads and generated quests track unresolved problems.","Journal records outcomes; World and current scenes surface relevant opportunities. Follow the named location and current stage.","Some quests expire or change if neglected. Completing a task can schedule later aftermath. Archives are bounded so old detail can be summarized while lasting consequences remain.","Read the current stage before taking an unrelated action. A rumor is not always an accepted quest.","story,time,world"],
 ["travel","Travel & exploration","World","World offers explicit destination travel; exploration examines the current area.","Choose a destination and read road consequences. Explore when you want local knowledge or discoveries.","Time, fatigue, road danger, skills, equipment and weather matter. Major discoveries are finite; travel may trigger combat.","Recover before a long journey. Clicking another navigation tab does not move the character to a new location.","weather,quests,combat"],
 ["weather","Weather, seasons & affinity","World","Climate evolves with time and can affect travel, encounters and affinity resonance.","Read the current weather in World and the affinity details in Growth. Choose suitable approaches for the conditions.","Seasons change every 30 days. Resonance does not bypass costs or make every attempt succeed. Environmental art and effects use a finite local library.","A rain effect reflects world weather; it is not another hidden weather system. Opening the weather panel gives no experience.","cultivation,travel,time"],
 ["world","The living-world simulation","World","NPC intentions, factions, economies and unresolved threads advance with actions.","Watch World, Journal and local follow-ups. The game keeps mechanical state whether narration is offline or connected.","Recent-event cooldowns reduce repetition. A connected narrator can phrase grounded outcomes more freely, but cannot overrule locations, memories or consequences.","Return to an unresolved local thread when its consequences mature. Real-world idle time does not simulate days while the app is closed.","quests,reputation,narrator"],
 ["save","Saving, loading & importing","Settings","This release uses a new save format and requires a new game.","Save writes browser storage; Export creates a JSON copy. Import accepts only this release’s schema and rejects incompatible files with a reason.","Local saves belong to the site/browser origin. Clearing site data can remove them; export before moving devices or hosts. An interrupted combat reload resumes settled state without replaying damage.","Export after a long session. A downloaded release ZIP is the game, not your campaign save.","offline,settings"],
 ["offline","Offline play & updates","Settings","Essential game assets are cached by the service worker after a successful online load.","Use HTTPS or localhost. Give the first visit time to finish caching before disconnecting. An updated build installs a versioned cache.","Offline support does not transfer saves between sites. iOS storage eviction remains a browser limitation. Missing first-load files cannot be conjured offline.","Load the game once online before a trip and export a backup. Opening index.html as file:// does not install a service worker.","save,music"],
 ["music","Music & sound","Settings","Calm and combat tracks crossfade with the current scene.","Preferences controls music enablement and volume. A tap or keypress unlocks browser audio.","Combat uses the more intense score; peaceful scenes use the calm track. Background suspension pauses playback, and local audio remains available offline.","If silent, tap once and check music enablement and volume. Lower music independently when reading a long conversation.","settings,offline"],
 ["settings","Accessibility & performance","Settings","Preferences provides text size, motion, sound and choice detail.","Use Large text, Reduced motion, or Faster combat according to your needs. The browser’s reduced-motion preference is also respected.","Reduced motion shortens animation waits. Scrolling is allowed; only modals need their own scroll region. Cosmetic quality does not change simulation outcomes.","Use Reduced motion if effects distract you. Keep scrolling to reach long entries rather than shrinking text beyond readability.","save,music"],
 ["glossary","Glossary & common questions","Basics","Qi: technique energy. Momentum: temporary combat advantage. Heat: dangerous attention.","Martial realm is overall cultivation. Mastery is 1–10 in a skill tier. Transcendence evolves a mastered skill into its next tier while keeping earned effectiveness.","Foundation, stability and deviation describe breakthrough readiness and condition. Cultivation insight is the single realm-progress measure; it is not an extra skill-training currency.","“Why did XP stop?” Check mastery 10, meaningful use, repeated approach, or an unresolved action. “Why is a technique unavailable?” Check that it is learned and affordable.","training,mastery,transcendence"],
 ["mastery","Why mastery stops at 10","Growth","Level 10 is the hard mastery cap for that skill’s current realm tier.","The skill remains usable at its earned strength. Advance your martial realm, then evolve an eligible mastered skill from Arts or Life.","XP at mastery 10 is not banked for the next tier. Advancing your realm never resets or automatically maxes unfinished skills.","A Mortal 10/10 technique stays Mortal 10/10 after a martial breakthrough until you choose its evolution. It does not become 11/10.","cultivation,transcendence,training"],
 ["transcendence","Skill transcendence","Growth","Transcendence is an evolution of the same mastered skill, preserving its identity and history.","After your realm advances, choose Evolve on an eligible 10/10 skill. The simple evolution action deepens Control, advances one skill tier and begins that tier at 1/10.","Its new 1/10 keeps the previous 10/10 baseline. Controlled technique forms add precision and defensive control. A skill cannot exceed your unlocked realm; noncombat effectiveness and recipe access retain their earned baseline.","If you skipped several martial realms, a skill still evolves one tier at a time. Nonmaxed skills keep their XP; new methods begin at 1/10 in your current realm.","mastery,cultivation,techniques"],
 ["realms","The martial realm ladder","Growth","Mortal → Third-Rate → Second-Rate → First-Rate → Peak → Transcendent → Profound → Life-and-Death → Heavenly.","Each step strengthens cultivation presence and unlocks the next tier for eligible mastered skills. Growth lists the next threshold and current readiness.","Higher realm is not automatic victory. Qi, injuries, equipment, learned methods, enemy intent and the actual challenge still matter.","A physician or craftsperson can earn cultivation insight through meaningful work. Realm advancement is not reserved for repeated sword drills.","cultivation,training,mastery"],
 ["narrator","Offline and connected narration","Story","Offline uses authored content and local rules. Connected mode calls a separately configured model service for narration.","Choose your narrative mode and response length in Preferences. Connected mode needs the configured server and provider access; game credentials are kept on that server.","Mechanics resolve and validate the outcome before narration. Failed or cancelled generation must not replay consequences. Live connected quality depends on the configured model and is not equivalent to offline templates.","If disconnected, retain your draft or use the clearly labeled offline mode. Never type an API key into a character’s dialogue. A convincing paragraph cannot grant a new realm.","freeform,offline,save"]
 ];
 let entries=[],history=[],selected='start',query='',category='All',spoilers=false,host=null;
 function configure(defs){entries=rows.map(([id,title,category,quick,use,cost,tip,related])=>({id,title,category,quick,use,cost,tip,related:related.split(',')}));
  for(const [name,t] of Object.entries(defs.techniques||{}))entries.push({id:'tech-'+name,title:name,category:'Techniques',quick:t.desc,use:`Arts: ${t.art}. Combat approach: ${t.mode}.`,cost:`Base Qi cost: ${t.cost||0}. Evolved forms and fates can modify this; the combat button shows your actual cost.`,tip:'Read enemy intent before committing. '+(t.defense?'Use this defensive method to preserve condition.':'Save enough Qi for the following exchange.'),related:['techniques','combat'],secret:!defs.known?.includes(name)});
  for(const [id,l] of Object.entries(defs.lineages||{}))entries.push({id:'sect-'+id,title:l.name,category:'Lineages',quick:l.desc,use:`Seek inheritance at ${l.locations.join(' or ')}. Related skill: ${l.skill}.`,cost:'Later inheritance depends on the displayed realm and standing requirements. Hostile faction relations can block access.',tip:'Go to Arts to see your current access reason and the next requirement.',related:['sects','training'],secret:!!l.forbidden});
  for(const r of defs.recipes||[])entries.push({id:'recipe-'+r.name,title:r.name,category:'Recipes',quick:'Crafting recipe from the active game catalogue.',use:`Life → appropriate workshop. Effective skill ${r.skill}; ${r.cost||0} silver. Materials: ${Object.entries(r.mats||{}).map(([name,qty])=>qty+' × '+name).join(', ')}. ${r.desc||''}`,cost:'The displayed ingredients, skill and currency requirements must be satisfied before crafting.',tip:'Check Bag after crafting and equip gear if appropriate.',related:['craft','bag']});
 }
 function markup(id='start'){selected=entries.some(x=>x.id===id)?id:'start';return `<section class="guideShell"><header class="guideHeader"><img class="cookieArt" src="./art/ui/cookie.webp" alt="Cookie, black cat with gold eyes and a crescent moon"><div><span class="eyebrow">COOKIE’S COMPENDIUM</span><h2>A little knowledge. A longer journey.</h2><p>Ask plainly, wanderer. I keep the rules beside the tea.</p></div></header><div class="guideControls"><label>Search the guide<input id="guideSearch" type="search" placeholder="Try Qi, clothier, or save" value="${e(query)}"></label><label>Category<select id="guideCategory">${['All',...new Set(entries.map(x=>x.category))].map(x=>`<option ${category===x?'selected':''}>${e(x)}</option>`).join('')}</select></label><label class="guideSpoilers"><input id="guideSpoilers" type="checkbox" ${spoilers?'checked':''}> Include undiscovered techniques and secrets</label></div><div class="guideColumns"><nav id="guideResults" aria-label="Guide topics"></nav><article id="guideArticle" tabindex="-1"></article></div></section>`}
 function results(){let list=entries.filter(x=>(spoilers||!x.secret)&&(category==='All'||x.category===category)&&(`${x.title} ${x.quick} ${x.use} ${x.cost} ${x.tip}`).toLowerCase().includes(query.toLowerCase()));host.querySelector('#guideResults').innerHTML=`<p role="status">${list.length} topics</p>`+list.map(x=>`<button class="guideTopic ${selected===x.id?'selected':''}" data-guide="${e(x.id)}">${e(x.title)}<small>${e(x.category)}</small></button>`).join('');host.querySelectorAll('[data-guide]').forEach(b=>b.onclick=()=>open(b.dataset.guide));}
 function article(){const x=entries.find(x=>x.id===selected)||entries[0];host.querySelector('#guideArticle').innerHTML=`<button id="guideBack" ${history.length?'':'disabled'}>← Previous topic</button><span class="eyebrow">${e(x.category)}</span><h2>${e(x.title)}</h2><p class="guideQuick">${e(x.quick)}</p><details open><summary>How to use it</summary><p>${e(x.use)}</p></details><details open><summary>Costs, restrictions & outcomes</summary><p>${e(x.cost)}</p></details><details><summary>Cookie’s example & common mistake</summary><p>${e(x.tip)}</p></details><h3>Related topics</h3>${x.related.map(id=>entries.find(t=>t.id===id)).filter(Boolean).map(t=>`<button data-related="${e(t.id)}">${e(t.title)}</button>`).join('')}`;host.querySelector('#guideBack').onclick=()=>{const id=history.pop();if(id)open(id,false)};host.querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>open(b.dataset.related));}
 function open(id,push=true){if(!host)return;if(push&&id!==selected){history.push(selected);history=history.slice(-30)}selected=id;article();results();host.querySelector('#guideArticle').scrollIntoView?.({block:'start'});}
 function bind(el){host=el;results();article();el.querySelector('#guideSearch').oninput=ev=>{query=ev.target.value;results()};el.querySelector('#guideCategory').onchange=ev=>{category=ev.target.value;results()};el.querySelector('#guideSpoilers').onchange=ev=>{spoilers=ev.target.checked;results()};}
 return {configure,markup,bind,open,inventory:()=>entries};
})();
