(function(root){
 'use strict';
 const catalog=Object.freeze({
  'spirit-fox':{id:'spirit-fox',species:'fox',name:'Moonglass Fox',role:'Qi companion',support:'Restores 2 / 3 / 4 Qi every second exchange.',cost:55,habitat:'Cloudveil Sect',stages:['Moonlit Kit','Twin-tail Guide','Moonglass Guardian']},
  'spirit-crane':{id:'spirit-crane',species:'crane',name:'Mistreed Crane',role:'Healing companion',support:'Restores 2 / 3 / 4 health every second exchange.',cost:65,habitat:'Hundred Herb Valley',stages:['Reedling','Mistwing','Silvercrest Guardian']},
  'spirit-tiger':{id:'spirit-tiger',species:'tiger',name:'Emberstripe Tiger',role:'Striking companion',support:'Adds 2 / 4 / 6 damage to a successful attack.',cost:80,habitat:'Red Moon Ruins',stages:['Ember Cub','Goldstripe Hunter','Dawnfire Guardian']},
  'spirit-turtle':{id:'spirit-turtle',species:'turtle',name:'Jadestone Turtle',role:'Protective companion',support:'Prevents 1 / 2 / 3 damage from a landed enemy strike.',cost:50,habitat:'Jade River City',stages:['Jade Hatchling','River Warden','Ancient Jade Guardian']}
 });
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number.isFinite(Number(v))?Math.floor(Number(v)):a));
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function ensure(S){
  if(!S?.player)return null;const p=S.player;p.equipment??={};
  if(!p.pets||typeof p.pets!=='object'||Array.isArray(p.pets))p.pets={};const a=p.pets;a.schema=1;a.serial=clamp(a.serial,0,1e9);
  if(!a.owned||typeof a.owned!=='object'||Array.isArray(a.owned))a.owned={};
  for(const id of Object.keys(a.owned)){if(!catalog[id]||!a.owned[id]||typeof a.owned[id]!=='object'){delete a.owned[id];continue}const x=a.owned[id];for(const [k,max]of Object.entries({stage:3,xp:180,bond:100,journeys:999,battles:999,day:1e7,dailyXP:16,dailyJourneys:3,restDay:1e7,exploreEvent:1e9,restEvent:1e9}))x[k]=clamp(x[k],k==='stage'?1:0,max);x.source=x.source==='encounter'?'encounter':'purchase';x.metDay=clamp(x.metDay,1,1e7);x.visited=Array.isArray(x.visited)?x.visited.filter(v=>typeof v==='string').slice(-3):[];}
  if(!a.trails||typeof a.trails!=='object'||Array.isArray(a.trails))a.trails={};for(const id of Object.keys(a.trails)){if(!catalog[id])delete a.trails[id];else{const t=a.trails[id];a.trails[id]={days:Array.isArray(t?.days)?[...new Set(t.days.filter(Number.isInteger).filter(n=>n>0))].slice(-2):[],lastEvent:clamp(t?.lastEvent,0,1e9)}}}
  a.notices=Array.isArray(a.notices)?a.notices.filter(x=>typeof x==='string').slice(-6).map(x=>x.slice(0,240)):[];
  if(!catalog[p.equipment.pet]||!a.owned[p.equipment.pet])p.equipment.pet=null;
  return a;
 }
 function owns(S,id){return !!ensure(S)?.owned[id]}
 function equipped(S){const a=ensure(S),id=S?.player?.equipment?.pet;if(!id||!a?.owned[id])return null;const x=a.owned[id];return {...catalog[id],...x,id,stageName:catalog[id].stages[x.stage-1]}}
 function blocked(S){if(S.combat)return 'Finish this fight before changing companions.';if(S.chat?.pendingId)return 'Finish the pending response first.';if(S.flow?.mode==='reaction')return 'Continue the current scene first.';return null}
 const fail=reason=>({ok:false,reason,text:reason});
 function notice(S,text){const a=ensure(S);a.notices.push(text);a.notices=a.notices.slice(-6);return text}
 function equip(S,id){const a=ensure(S),why=blocked(S);if(why)return fail(why);if(id!==null&&!a.owned[id])return fail('That spirit has not joined you.');if(S.player.equipment.pet===id)return fail('That companion is already selected.');S.player.equipment.pet=id;return {ok:true,text:notice(S,id?`${catalog[id].name} travels beside you.`:'Your spirit companion waits safely while you travel alone.')}}
 function acquire(S,id,{source='purchase'}={}){const a=ensure(S),c=catalog[id],why=blocked(S);if(why)return fail(why);if(!c)return fail('Unknown spirit.');if(a.owned[id])return fail('This spirit has already joined you.');if(source==='encounter'){if(S.world.location!==c.habitat||(a.trails[id]?.days.length||0)<2)return fail(`Explore ${c.habitat} on two different days to earn this spirit’s trust.`)}else{if(source!=='purchase')return fail('Unknown adoption source.');if(S.world.location!=='Ten Thousand Lantern Market')return fail('The spirit keeper waits at Ten Thousand Lantern Market.');if(S.player.silver<c.cost)return fail(`Adoption and supplies cost ${c.cost} silver.`);S.player.silver-=c.cost}
  a.owned[id]={stage:1,xp:0,bond:2,journeys:0,battles:0,source,metDay:S.world.day,day:S.world.day,dailyXP:0,dailyJourneys:0,restDay:0,exploreEvent:0,restEvent:0,visited:[]};if(!S.player.equipment.pet)S.player.equipment.pet=id;S.actionNo=(S.actionNo||0)+1;
  return {ok:true,id,text:notice(S,`${c.name} joins you as a ${c.stages[0]}. ${source==='purchase'?`${c.cost} silver paid to the spirit keeper.`:'Your patient visits earned its trust.'}`)};
 }
 function day(S,x){if(x.day!==S.world.day){x.day=S.world.day;x.dailyXP=0;x.dailyJourneys=0;x.visited=[]}}
 function grow(S,x,xp,bond=0){day(S,x);const grant=Math.min(xp,16-x.dailyXP,180-x.xp);x.xp+=Math.max(0,grant);x.dailyXP+=Math.max(0,grant);x.bond=clamp(x.bond+bond,0,100);return grant}
 function explore(S,{eventId}={}){const a=ensure(S);if(!Number.isInteger(eventId)||eventId!==S.actionNo||eventId<1)return fail('Exploration has not resolved.');const notices=[];for(const c of Object.values(catalog)){if(a.owned[c.id]||S.world.location!==c.habitat)continue;const t=a.trails[c.id]??={days:[],lastEvent:0};if(eventId<=t.lastEvent)continue;t.lastEvent=eventId;if(!t.days.includes(S.world.day)&&t.days.length<2){t.days.push(S.world.day);const text=t.days.length===2?`${c.name} now approaches without fear. You may invite it to join you from Inventory → Spirit companions.`:`You notice a ${c.stages[0].toLowerCase()} along the route. Return on another day to earn its trust.`;notices.push(notice(S,text))}}
  const pet=equipped(S);if(!pet)return {ok:true,text:notices.join(' ')};const x=a.owned[pet.id];if(eventId<=x.exploreEvent)return {ok:false,text:''};x.exploreEvent=eventId;day(S,x);if(x.dailyJourneys>=3||x.visited.includes(S.world.location))return {ok:true,text:notices.join(' ')};x.dailyJourneys++;x.visited.push(S.world.location);x.journeys++;grow(S,x,3,1);return {ok:true,text:notices.join(' ')};
 }
 function rest(S,{eventId,meaningful=false}={}){const pet=equipped(S);if(!pet||!meaningful||eventId!==S.actionNo)return {ok:false};const x=S.player.pets.owned[pet.id];if(eventId<=x.restEvent||x.restDay===S.world.day)return {ok:false};x.restEvent=eventId;x.restDay=S.world.day;grow(S,x,0,1);return {ok:true,text:`${pet.name} settles beside you while you recover.`}}
 function beginCombat(S){const a=ensure(S),c=S.combat;if(!c)return null;if(!c.petLedger||typeof c.petLedger!=='object'||Array.isArray(c.petLedger))c.petLedger={id:++a.serial,lastRound:0,lastEvent:0,exchanges:0,growthRounds:0,finished:false,companion:S.player.equipment.pet};const l=c.petLedger;for(const k of ['id','lastRound','lastEvent','exchanges'])l[k]=clamp(l[k],0,1e9);l.growthRounds=clamp(l.growthRounds,0,3);l.finished=l.finished===true;if(l.companion&&!a.owned[l.companion])l.companion=null;return l}
 function support(S,{eventId,mode,enemyDamage=0,playerDamage=0}={}){
  const c=S.combat,pet=equipped(S),none={ok:false,damage:0,guard:0,healing:0,qi:0,text:''};if(!c||!pet||!['sword','frost','unarmed','qi','focus','defend','breath','power'].includes(mode)||![S.actionNo,S.actionNo+1].includes(eventId))return none;const ledger=beginCombat(S);if(ledger.finished||ledger.companion!==pet.id||eventId<=ledger.lastEvent||c.round<=ledger.lastRound)return none;ledger.lastEvent=eventId;ledger.lastRound=c.round;ledger.exchanges++;
  const result={...none,ok:true,id:pet.id,stage:pet.stage,pose:'idle'},stage=pet.stage,alive=c.playerHp>0,enemyAlive=c.enemyHp>0;
  if(pet.species==='turtle'&&playerDamage>0){result.guard=Math.min(playerDamage,stage);result.text=`${pet.name} intercepts ${result.guard} damage.`}
  else if(alive&&enemyAlive&&pet.species==='tiger'&&enemyDamage>0){result.damage=stage*2;result.text=`${pet.name} strikes for ${result.damage} damage.`}
  else if(alive&&pet.species==='crane'&&ledger.exchanges%2===0){result.healing=Math.min(stage+1,Math.max(0,S.player.maxHp-c.playerHp));if(result.healing)result.text=`${pet.name} restores ${result.healing} health.`}
  else if(alive&&pet.species==='fox'&&ledger.exchanges%2===0){result.qi=Math.min(stage+1,Math.max(0,S.player.maxQi-S.player.qi));if(result.qi)result.text=`${pet.name} restores ${result.qi} Qi.`}
  if(result.text)result.pose='support';
  // Guarding an already harmless opponent and repeating idle Qi recovery cannot farm growth.
  if(alive&&c.difficulty>=5&&(enemyDamage>0||playerDamage>0)&&ledger.growthRounds<3){ledger.growthRounds++;grow(S,S.player.pets.owned[pet.id],2,ledger.growthRounds===1?1:0)}
  return result;
 }
 function finishCombat(S,{won}={}){const c=S.combat,ledger=c?.petLedger;if(!ledger||ledger.finished)return {ok:false};ledger.finished=true;const x=ensure(S).owned[ledger.companion];if(!x||ledger.growthRounds<1)return {ok:false};x.battles=clamp(x.battles+1,0,999);grow(S,x,won===true?3:1,won===true?1:0);return {ok:true}}
 function evolutionCheck(S,id){const x=ensure(S).owned[id];if(!x)return fail('This spirit has not joined you.');if(x.stage===3)return fail('This spirit has reached its final form.');const req=x.stage===1?{xp:24,bond:10,journeys:3,battles:1}:{xp:80,bond:30,journeys:8,battles:4};const missing=Object.entries(req).filter(([k,v])=>x[k]<v).map(([k,v])=>`${k}: ${x[k]}/${v}`);return {ok:missing.length===0,requirements:req,reason:missing.length?missing.join(' · '):'Ready to evolve',nextStage:x.stage+1}}
 function evolve(S,id){const why=blocked(S);if(why)return fail(why);const check=evolutionCheck(S,id);if(!check.ok)return check;const x=S.player.pets.owned[id];x.stage++;S.actionNo=(S.actionNo||0)+1;return {ok:true,text:notice(S,`${catalog[id].name} evolves into ${catalog[id].stages[x.stage-1]}. Your shared journeys have changed it.`)}}
 function asset(id,stage=1,pose='idle'){const c=catalog[id];return c?`art/pets/${c.species}/stage-${clamp(stage,1,3)}-${pose==='support'?'support':'idle'}.webp`:null}
 function render(S,{pose='idle',className=''}={}){const p=equipped(S);if(!p)return '';return `<span class="spiritPet spiritPet--${p.species} spiritPet--${pose==='support'?'support':'idle'} ${esc(className)}" data-pet="${p.id}" data-stage="${p.stage}" role="img" aria-label="${esc(p.name+' — '+p.stageName)}"><img src="${asset(p.id,p.stage,pose)}" alt="" decoding="async"></span>`}
 function panel(S){const a=ensure(S),active=S.player.equipment.pet,why=blocked(S);return `<section class="petPanel" aria-label="Spirit companions"><h3>Spirit companions</h3><p>One spirit travels beside you. Shared journeys and real exchanges help it grow; rest strengthens your bond. No feeding chores.</p><div class="petRoster">${Object.values(catalog).map(c=>{const x=a.owned[c.id],check=x&&evolutionCheck(S,c.id),trail=a.trails[c.id]?.days.length||0,canMeet=S.world.location===c.habitat&&trail>=2,canBuy=S.world.location==='Ten Thousand Lantern Market';return `<article class="petCard ${active===c.id?'equipped':''}"><img src="${asset(c.id,x?.stage||1)}" alt="${esc(c.name)}" loading="lazy" decoding="async"><div><h4>${esc(c.name)}</h4><p class="muted">${esc(x?c.stages[x.stage-1]:c.role)}</p><p>${esc(c.support)}</p>${x?`<p class="petGrowth">Bond ${x.bond}/100 · Growth ${x.xp}/180 · Journeys ${x.journeys} · Battles ${x.battles}</p><button data-pet-command="equip" data-pet-id="${active===c.id?'':c.id}" ${why?'disabled':''}>${active===c.id?'Let rest':'Travel together'}</button>${x.stage<3?`<button data-pet-command="evolve" data-pet-id="${c.id}" ${why||!check.ok?'disabled':''}>Evolve</button><small>${esc(check.reason)}</small>`:'<small>Final form</small>'}`:`<p class="muted">Explore ${esc(c.habitat)} on two different days (${trail}/2), or adopt at Ten Thousand Lantern Market.</p><button data-pet-command="${canMeet?'encounter':'purchase'}" data-pet-id="${c.id}" ${why||!(canMeet||canBuy)||!canMeet&&S.player.silver<c.cost?'disabled':''}>${canMeet?'Invite to join you':`Adopt · ${c.cost} silver`}</button>`}</div></article>`}).join('')}</div><p class="petStatus" role="status">${esc(a.notices.at(-1)||'Your first companion is waiting somewhere in the Jianghu.')}</p></section>`}
 function bind(S,{root:host=globalThis.document,onChange=()=>{}}={}){for(const b of host?.querySelectorAll?.('[data-pet-command]')||[])b.onclick=()=>{const id=b.dataset.petId||null,command=b.dataset.petCommand,result=command==='equip'?equip(S,id):command==='evolve'?evolve(S,id):acquire(S,id,{source:command});onChange(result);return result}}
 const api={catalog,ensure,owns,equipped,equip,acquire,explore,rest,beginCombat,support,finishCombat,evolutionCheck,evolve,asset,render,panel,bind};root.MURIM_PETS=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
