'use strict';
const fs=require('node:fs'),path=require('node:path');
const error=(code,message,status=429)=>Object.assign(Error(message),{code,status,public:true});
const finite=(x,fallback)=>x!==null&&x!==undefined&&!(typeof x==='string'&&!x.trim())&&Number.isFinite(Number(x))&&Number(x)>=0?Number(x):fallback;
const object=x=>x!==null&&typeof x==='object'&&!Array.isArray(x),nonnegative=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0;
function validateLedger(data){
 if(!object(data)||data.schema!==1||!object(data.periods)||!object(data.turns)||(data.identities!==undefined&&!object(data.identities)))throw error('BUDGET_INVALID','The usage ledger needs attention. Hosted requests are disabled.',503);
 for(const b of Object.values(data.periods))if(!object(b)||!['spent','requests','inputTokens','outputTokens','cacheHits','uncertain'].every(k=>nonnegative(b[k])))throw error('BUDGET_INVALID','Invalid budget totals; hosted requests are disabled.',503);
 for(const turn of Object.values(data.turns))if(!object(turn)||!['pending','complete','uncertain'].includes(turn.status)||!Object.hasOwn(data.periods,turn.period)||!['reserved','inputTokens','outputTokens','inputRate','outputRate','created','expires'].every(k=>nonnegative(turn[k])))throw error('BUDGET_INVALID','Invalid request ledger; hosted requests are disabled.',503);
 return data;
}
function periodKey(time,period){const iso=new Date(time).toISOString();return period==='month'?iso.slice(0,7):iso.slice(0,10)}
class Budget{
 constructor(options={}){this.file=options.file||null;this.now=options.now||Date.now;this.memory={schema:1,periods:{},turns:{}};this.config={limitUsd:finite(options.limitUsd,0),period:options.period==='month'?'month':'day',inputRate:finite(options.inputRate,null),outputRate:finite(options.outputRate,null),requestLimit:Math.max(1,Math.min(Number(options.requestLimit)||40,1000)),inputLimit:Math.max(1000,Math.min(Number(options.inputLimit)||12000,100000)),outputLimit:Math.max(64,Math.min(Number(options.outputLimit)||1100,4000)),concurrency:Math.max(1,Math.min(Number(options.concurrency)||1,8))};}
 locked(fn){let fd,lock=this.file&&this.file+'.lock';if(this.file){fs.mkdirSync(path.dirname(this.file),{recursive:true});try{fd=fs.openSync(lock,'wx');fs.writeFileSync(fd,JSON.stringify({pid:process.pid,time:this.now()}));}catch(e){if(e.code!=='EEXIST')throw e;let stale=false;try{const data=JSON.parse(fs.readFileSync(lock,'utf8'));if(!Number.isSafeInteger(data.pid)||data.pid<=0)throw Error('Malformed lock');try{process.kill(data.pid,0)}catch(e){stale=e.code==='ESRCH'}}catch{stale=fs.statSync(lock).mtimeMs<this.now()-30000}if(stale){fs.unlinkSync(lock);return this.locked(fn)}throw error('BUDGET_BUSY','The usage ledger is busy. No request was dispatched.',409);}}
  try{let data;try{data=this.file&&fs.existsSync(this.file)?JSON.parse(fs.readFileSync(this.file,'utf8')):this.memory;}catch{throw error('BUDGET_INVALID','The usage ledger could not be read. Hosted requests are disabled.',503);}validateLedger(data);const result=fn(data);if(this.file){const temporary=this.file+'.'+process.pid+'.tmp';fs.writeFileSync(temporary,JSON.stringify(data));fs.renameSync(temporary,this.file);}else this.memory=data;return result;}finally{if(fd!==undefined){fs.closeSync(fd);fs.unlinkSync(lock);}}}
 bucket(data){const key=periodKey(this.now(),this.config.period);return [key,data.periods[key]??={spent:0,requests:0,inputTokens:0,outputTokens:0,cacheHits:0,uncertain:0}];}
 expire(data){for(const turn of Object.values(data.turns))if(turn.status==='pending'&&turn.expires<this.now()){turn.status='uncertain';const b=data.periods[turn.period];if(b)b.uncertain++;}}
 status(){return this.locked(data=>{this.expire(data);const [period,b]=this.bucket(data),c=this.config;return {limitUsd:c.limitUsd,remainingUsd:Math.max(0,c.limitUsd-b.spent),reservedOrEstimatedUsd:b.spent,period,periodKind:c.period,requests:b.requests,requestLimit:c.requestLimit,inputTokens:b.inputTokens,outputTokens:b.outputTokens,uncertainRequests:b.uncertain,cacheHits:b.cacheHits,active:Object.values(data.turns).filter(t=>t.status==='pending').length,concurrency:c.concurrency,pricingConfigured:c.inputRate!==null&&c.outputRate!==null,enabled:c.limitUsd>0&&c.inputRate!==null&&c.outputRate!==null,billingNote:'Estimates using configured token rates; uncertain calls retain their maximum reservation. Provider billing is authoritative.'}});}
 reserve({key,identity=key,inputTokens,outputTokens,ttlMs=50000}){if([key,identity].some(x=>typeof x!=='string'||!x.length||x.length>256||['__proto__','constructor','prototype'].includes(x)))throw error('INVALID_ID','A valid settled-action identifier is required.',400);if(!Number.isFinite(ttlMs)||ttlMs<1||ttlMs>120000)throw error('INVALID_LEASE','The request lease is invalid.',400);return this.locked(data=>{this.expire(data);const [period,b]=this.bucket(data),c=this.config,previous=data.turns[key];data.identities??={};if(Object.hasOwn(data.identities,identity)&&data.identities[identity]!==key)throw error('ID_CONFLICT','This settled turn was already submitted with different narration settings or context. Expand it with a new turn ID instead of retrying a changed request.',409);if(previous){if(previous.status==='complete'&&previous.result){b.cacheHits++;return {cached:previous.result,key};}throw error(previous.status==='pending'?'ALREADY_PENDING':'UNCERTAIN_PRIOR_REQUEST',previous.status==='pending'?'This settled turn already has a request in progress.':'An earlier request may have been billed. It will not be dispatched again; use the saved offline outcome.',409);}
  if(c.limitUsd<=0)throw error('BUDGET_ZERO','Hosted narration is disabled: the configured spending limit is zero.');if(c.inputRate===null||c.outputRate===null)throw error('PRICING_REQUIRED','Explicit input and output token prices are required before hosted narration can run.',503);
  if(!Number.isSafeInteger(inputTokens)||!Number.isSafeInteger(outputTokens)||inputTokens<0||outputTokens<1||inputTokens>c.inputLimit||outputTokens>c.outputLimit)throw error('TOKEN_LIMIT','The scene exceeds the configured input or output limit.');if(b.requests>=c.requestLimit)throw error('REQUEST_LIMIT','The request limit for this period has been reached.');if(Object.values(data.turns).filter(t=>t.status==='pending').length>=c.concurrency)throw error('CONCURRENCY_LIMIT','The narrator is busy with another reserved request. No new request was dispatched.');
  const reserved=(inputTokens*c.inputRate+outputTokens*c.outputRate)/1e6;if(b.spent+reserved>c.limitUsd+1e-12)throw error('BUDGET_EXCEEDED','This request could exceed the remaining budget. Use the settled offline outcome.');b.spent+=reserved;b.requests++;data.identities[identity]=key;data.turns[key]={status:'pending',period,reserved,inputTokens,outputTokens,inputRate:c.inputRate,outputRate:c.outputRate,created:this.now(),expires:this.now()+ttlMs};return {key,reserved};});}
 complete(key,result,usage){return this.locked(data=>{const turn=data.turns[key];if(!turn||turn.status!=='pending')return;const b=data.periods[turn.period],known=Number.isSafeInteger(usage?.input_tokens)&&usage.input_tokens>=0&&Number.isSafeInteger(usage?.output_tokens)&&usage.output_tokens>=0;let cost=turn.reserved;if(known){cost=(usage.input_tokens*turn.inputRate+usage.output_tokens*turn.outputRate)/1e6;b.inputTokens+=usage.input_tokens;b.outputTokens+=usage.output_tokens;}else b.uncertain++;b.spent=Math.max(0,b.spent-turn.reserved+cost);Object.assign(turn,{status:'complete',result,cost,usage:known?{input_tokens:usage.input_tokens,output_tokens:usage.output_tokens}:null,usageEstimated:!known,completed:this.now()});return {estimatedUsd:cost,usageKnown:known};});}
 uncertain(key){return this.locked(data=>{const turn=data.turns[key];if(turn?.status==='pending'){turn.status='uncertain';data.periods[turn.period].uncertain++;}});}
}
module.exports={Budget,periodKey};
