'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),zlib=require('node:zlib');
const Encounter=require('../encounters.js'),Client=require('../encounter-art.js'),{Budget}=require('./budget.cjs'),PROMPT=require('./encounter-art-prompt.json');
const ENDPOINT='https://api.openai.com/v1/images/generations',MAX_PNG=6*1024*1024,MAX_RESPONSE=9*1024*1024;
const error=(code,message,status=502)=>Object.assign(Error(message),{code,status,public:true});
const number=(v,f)=>v!==undefined&&v!==null&&String(v).trim()!==''&&Number.isFinite(Number(v))&&Number(v)>=0?Number(v):f;
function configuration(env=process.env){const enabled=env.LM_IMAGE_ENABLED==='true',provider=String(env.LM_IMAGE_PROVIDER||''),model=String(env.LM_IMAGE_MODEL||'').trim(),key=String(env.LM_IMAGE_API_KEY||''),maximumUsd=number(env.LM_IMAGE_MAX_USD_PER_IMAGE,0);return {enabled,provider,model,key,endpoint:ENDPOINT,ready:enabled&&provider==='openai'&&/^gpt-image-[a-z0-9.-]{1,80}$/.test(model)&&!!key&&maximumUsd>0,quality:['low','medium','high'].includes(env.LM_IMAGE_QUALITY)?env.LM_IMAGE_QUALITY:'low',maximumUsd,limitUsd:number(env.LM_IMAGE_BUDGET_USD,0),period:env.LM_IMAGE_BUDGET_PERIOD==='month'?'month':'day',requestLimit:Math.max(1,Math.min(100,Math.floor(number(env.LM_IMAGE_REQUESTS_PER_PERIOD,8)))),concurrency:1,timeoutMs:Math.max(1000,Math.min(90000,number(env.LM_IMAGE_TIMEOUT_MS,80000))),cacheBytes:Math.max(16,Math.min(256,number(env.LM_IMAGE_CACHE_MB,64)))*1024*1024,budgetFile:env.LM_IMAGE_BUDGET_FILE||path.join(__dirname,'.runtime','image-usage.json'),cacheDir:env.LM_IMAGE_CACHE_DIR||path.join(__dirname,'.runtime','encounter-art')};}
function validateRequest(value){if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!['receipt','consent'].includes(k))||value.consent!==true)throw error('ART_CONSENT_REQUIRED','A deliberate image request with explicit artwork consent is required.',400);try{return {receipt:Client.validateReceipt(value.receipt)}}catch(e){throw error('INVALID_ART_RECEIPT',e.message,400)}}
const role={bandit:'road bandit in worn practical robes; no stolen valuables',vagabond:'travel-worn wandering vagabond with plain robes',student:'young adult martial student in disciplined training robes',guard:'adult road guard in practical reinforced robes',merchant:'traveling merchant in modest well-kept robes; no treasure display',traveler:'ordinary passing traveler in functional layered robes'};
const hair={male:['Warrior Topknot: tied high knot with long back hair','Scholar Curtains: center-parted curtain fringe and flowing back hair','Low Martial Tail: practical low-tied long ponytail','Layered Martial Cut: short layered martial hair','Swept Short Fringe: short hair swept to one side','Cropped Cultivator: cropped tousled hair'],female:['Jade Coiled Bun: coiled high bun with ornaments','Long Scholar Silk: long straight flowing hair','Braided Side Tail: long braid gathered to one side','Layered Bob: short layered bob','Short Martial Tie: short tied-back hair','Cropped Side Fringe: cropped hair with a side fringe']};
const palettes=['Navy #26384a with muted gold trim','Crimson #4b272b with muted gold trim','Jade #315342 with muted gold trim','Earth #40372f with warm brown trim','Plum #333047 with pale silver-blue trim','Gold #5a4f31 with restrained golden trim','Charcoal #26262a with muted gold trim','Ivory #d7d2c7 with brown-gold trim'];
function providerBody(payload,config){const n=payload.receipt.encounter,a=n.appearance,wardrobe=Encounter.visual(n),spec={outfitFamily:wardrobe.outfit,headwear:wardrobe.head||"uncovered head",adultBody:a.body,role:role[n.archetype],face:['gentle oval face','angular focused face','mature composed face'][a.face-1],hair:hair[a.body][a.hair-1],clothingPalette:palettes[a.palette]};return {model:config.model,prompt:PROMPT.instructions+'\nEstablished visual specification: '+JSON.stringify(spec),n:1,size:'1024x1024',quality:config.quality,background:'transparent',output_format:'png',moderation:'auto',stream:false};}
function cacheIdentity(payload,config){return crypto.createHash('sha256').update(JSON.stringify({promptVersion:PROMPT.version,provider:config.provider,model:config.model,quality:config.quality,size:'1024x1024',receipt:payload.receipt})).digest('hex');}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
const crc=bytes=>{let n=0xffffffff;for(const b of bytes)n=crcTable[(n^b)&255]^(n>>>8);return(n^0xffffffff)>>>0;};
function validatePng(bytes){
 if(!Buffer.isBuffer(bytes)||bytes.length<60||bytes.length>MAX_PNG||!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))throw error('INVALID_ART_RESPONSE','The provider did not return a supported PNG cutout.');
 let at=8,header=false,end=false,idat=[],kept=[bytes.subarray(0,8)];while(at+12<=bytes.length){const length=bytes.readUInt32BE(at),type=bytes.toString('ascii',at+4,at+8),stop=at+12+length;if(length>MAX_PNG||stop>bytes.length||!/^[A-Za-z]{4}$/.test(type)||crc(bytes.subarray(at+4,stop-4))!==bytes.readUInt32BE(stop-4))throw error('INVALID_ART_RESPONSE','The provider image was malformed.');const data=bytes.subarray(at+8,stop-4);
  if(!header){if(type!=='IHDR'||length!==13||data.readUInt32BE(0)!==1024||data.readUInt32BE(4)!==1024||data[8]!==8||data[9]!==6||data[10]!==0||data[11]!==0||data[12]!==0)throw error('INVALID_ART_RESPONSE','A 1024-square non-animated transparent RGBA PNG is required.');header=true;kept.push(bytes.subarray(at,stop));}
  else if(type==='IDAT'){idat.push(data);kept.push(bytes.subarray(at,stop));}
  else if(type==='IEND'){if(length||!idat.length||stop!==bytes.length)throw error('INVALID_ART_RESPONSE','The provider image was incomplete.');end=true;kept.push(bytes.subarray(at,stop));break;}
  else if(type==='IHDR'||['acTL','fcTL','fdAT'].includes(type)||type[0]===type[0].toUpperCase())throw error('INVALID_ART_RESPONSE','Unsupported image content was rejected.');
  at=stop;
 }
 if(!end)throw error('INVALID_ART_RESPONSE','The provider image was incomplete.');let pixels;try{pixels=zlib.inflateSync(Buffer.concat(idat),{maxOutputLength:1024*(1024*4+1)});}catch{throw error('INVALID_ART_RESPONSE','The provider PNG could not be decoded.');}if(pixels.length!==1024*(1024*4+1))throw error('INVALID_ART_RESPONSE','The provider image dimensions did not match its pixels.');for(let row=0;row<1024;row++)if(pixels[row*(1024*4+1)]>4)throw error('INVALID_ART_RESPONSE','The provider PNG scanlines were malformed.');return Buffer.concat(kept);
}
async function generate(payload,{config,signal,fetch:request=fetch}){const response=await request(ENDPOINT,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',Authorization:'Bearer '+config.key},body:JSON.stringify(providerBody(payload,config)),signal});if(!response.ok)throw error(response.status===401||response.status===403?'ART_CREDENTIALS_REJECTED':'ART_PROVIDER_UNAVAILABLE','The image provider could not complete this portrait. Local artwork remains available.');if(!String(response.headers.get('content-type')).includes('application/json')||!response.body?.getReader)throw error('INVALID_ART_RESPONSE','The provider returned an unsupported artwork response.');const reader=response.body.getReader(),chunks=[];let count=0;try{for(;;){const part=await reader.read();if(part.done)break;count+=part.value.byteLength;if(count>MAX_RESPONSE)throw error('INVALID_ART_RESPONSE','The image response exceeded its size limit.');chunks.push(Buffer.from(part.value));}}finally{await reader.cancel().catch(()=>{});}let data;try{data=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw error('INVALID_ART_RESPONSE','The image provider returned malformed JSON.');}if(!Array.isArray(data.data)||data.data.length!==1||typeof data.data[0]?.b64_json!=='string'||data.data[0].url)throw error('INVALID_ART_RESPONSE','Only one embedded PNG is accepted; remote URLs are not loaded.');const encoded=data.data[0].b64_json,bytes=Buffer.from(encoded,'base64');if(bytes.toString('base64')!==encoded)throw error('INVALID_ART_RESPONSE','The provider image encoding was invalid.');return validatePng(bytes);}
class ImageBudget{
 constructor(config,now){this.config=config;this.ledger=new Budget({file:config.budgetFile||null,now,limitUsd:config.limitUsd,period:config.period,inputRate:0,outputRate:config.maximumUsd>0?config.maximumUsd*1e6:null,requestLimit:config.requestLimit,inputLimit:1000,outputLimit:64,concurrency:1});}
 status(){const s=this.ledger.status();return {limitUsd:s.limitUsd,remainingUsd:s.remainingUsd,reservedMaximumUsd:s.reservedOrEstimatedUsd,period:s.period,periodKind:s.periodKind,requests:s.requests,requestLimit:s.requestLimit,maximumUsdPerImage:this.config.maximumUsd,active:s.active,cacheHits:s.cacheHits,unreconciledRequests:s.uncertainRequests,enabled:this.config.enabled&&this.config.ready&&s.enabled,billingNote:'Each dispatched image retains its configured maximum reservation, including uncertain calls. This is a conservative host estimate, not provider billing.'};}
 reserve(key,identity){try{return this.ledger.reserve({key,identity,inputTokens:0,outputTokens:1,ttlMs:this.config.timeoutMs+10000});}catch(e){const messages={BUDGET_ZERO:'The separate image budget is $0. Local artwork remains active.',PRICING_REQUIRED:'Set a conservative maximum cost per image before enabling generation.',BUDGET_EXCEEDED:'The separate image budget cannot cover another portrait.',REQUEST_LIMIT:'The image request limit has been reached.',CONCURRENCY_LIMIT:'Another portrait is being generated; no new image request was dispatched.',UNCERTAIN_PRIOR_REQUEST:'This portrait may already have been billed. It will not be requested again automatically; use local artwork.',ID_CONFLICT:'This encounter was already requested with different artwork settings. Keep its existing art; it will not be billed again.'};if(messages[e.code])e.message=messages[e.code];throw e;}}
 complete(key,result){return this.ledger.complete(key,result,null);}
 uncertain(key){return this.ledger.uncertain(key);}
}
function createService(options={}){
 const config=options.config||configuration(),budget=options.budget||new ImageBudget(config,options.now||Date.now),dir=path.resolve(config.cacheDir||path.join(__dirname,'.runtime','encounter-art'));
 function fileFor(key){if(!/^[a-f0-9]{64}$/.test(key))throw error('ART_NOT_FOUND','Portrait not found.',404);return path.join(dir,key+'.png');}
 function read(key){const file=fileFor(key);try{const stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>MAX_PNG)throw Error('Invalid cache file');return fs.readFileSync(file);}catch{throw error('ART_NOT_FOUND','The cached portrait is unavailable. Local artwork remains active.',404);}}
 async function request(value,{signal,fetch:requestFetch}={}){
  const payload=validateRequest(value);if(!config.ready||config.enabled!==true||config.endpoint!==ENDPOINT)throw error('ART_NOT_CONFIGURED','Optional generated portraits are disabled or not configured. Local artwork remains active.',503);
  if(signal?.aborted)throw error('ART_CANCELLED','The image request was cancelled before dispatch.',400);
  const key=cacheIdentity(payload,config);fs.mkdirSync(dir,{recursive:true});if(!fs.existsSync(fileFor(key))){let bytes=0;for(const name of fs.readdirSync(dir)){if(/^[a-f0-9]{64}\.png$/.test(name)){const st=fs.lstatSync(path.join(dir,name));if(st.isFile()&&!st.isSymbolicLink())bytes+=st.size;}}if(bytes+MAX_PNG>config.cacheBytes)throw error('ART_CACHE_FULL','The portrait cache is full. Local artwork remains available.',507);}
  let reservation=budget.reserve(key,payload.receipt.id),timer,controller;
  if(reservation.cached){read(key);return {...reservation.cached,cacheHit:true};}
  try{
   controller=new AbortController();const abort=()=>controller.abort(signal?.reason);if(signal?.aborted)abort();else signal?.addEventListener('abort',abort,{once:true});timer=setTimeout(()=>controller.abort('timeout'),config.timeoutMs);let png;
   try{if(controller.signal.aborted)throw error('ART_CANCELLED','The image request was cancelled.');png=await generate(payload,{config,signal:controller.signal,fetch:requestFetch||options.fetch});}finally{signal?.removeEventListener('abort',abort);}
   if(controller.signal.aborted)throw error('ART_INTERRUPTED','Artwork generation was interrupted.');const file=fileFor(key),temporary=file+'.'+process.pid+'.tmp';fs.writeFileSync(temporary,png,{flag:'wx'});fs.renameSync(temporary,file);const result={ok:true,url:`/api/encounter-art/cache/${key}.png`,encounterId:payload.receipt.encounter.id,receiptId:payload.receipt.id,cacheKey:key,cacheHit:false,promptVersion:PROMPT.version,reservationUsd:config.maximumUsd};budget.complete(key,result);reservation=null;return result;
  }catch(e){if(reservation)budget.uncertain(key);if(controller?.signal.aborted)throw error('ART_INTERRUPTED','Artwork generation was interrupted. Local art remains active; the dispatched reservation is retained.',504);throw e;}finally{clearTimeout(timer);}
 }
 return {config,budget,status:()=>{const usage=budget.status();return {ready:config.ready&&usage.enabled&&usage.remainingUsd>=config.maximumUsd&&usage.requests<usage.requestLimit,provider:config.ready?config.provider:null,model:config.ready?config.model:null,promptVersion:PROMPT.version,budget:usage,defaultMode:'local artwork'};},request,read};
}
module.exports={configuration,validateRequest,providerBody,cacheIdentity,validatePng,generate,ImageBudget,createService,PROMPT,ENDPOINT,MAX_PNG};

