'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const Narrative=require('../narrative.js');
const EncounterArt=require('./encounter-art.cjs');
const {Budget}=require('./budget.cjs'),PROMPT=require('./storyteller-prompt.json'),INSTRUCTIONS=PROMPT.instructions;
const safeError=(code,message,status=502)=>Object.assign(new Error(message),{code,status,public:true});
const endpointValid=(endpoint,local=false)=>{try{const u=new URL(endpoint),loopback=['127.0.0.1','localhost','[::1]'].includes(u.hostname);return !u.username&&!u.password&&(local?loopback&&(u.protocol==='http:'||u.protocol==='https:'):u.protocol==='https:'||loopback&&u.protocol==='http:')}catch{return false}};
function configuration(env=process.env){
 const provider=String(env.LM_NARRATOR_PROVIDER||'').trim(),model=String(env.LM_NARRATOR_MODEL||'').trim(),key=String(env.LM_NARRATOR_API_KEY||''),origin=String(env.LM_PUBLIC_ORIGIN||'').trim();
 let endpoint=provider==='openai'?'https://api.openai.com/v1/responses':String(env.LM_NARRATOR_URL||'').trim(),valid=['openai','responses-compatible'].includes(provider)&&!!model&&model.length<=100;
 valid=valid&&endpointValid(endpoint);
 if(provider==='openai'&&!key)valid=false;
 const local={provider:'local Responses-compatible',model:String(env.LM_LOCAL_MODEL||'').trim(),endpoint:String(env.LM_LOCAL_URL||'').trim(),key:String(env.LM_LOCAL_API_KEY||'')};local.ready=!!local.model&&endpointValid(local.endpoint,true);
 return {provider,model,key,endpoint,origin,ready:!!valid,local,timeoutMs:Math.max(1000,Math.min(Number(env.LM_NARRATOR_TIMEOUT_MS)||40000,90000)),budget:{limitUsd:env.LM_BUDGET_USD??0,period:env.LM_BUDGET_PERIOD||'day',inputRate:env.LM_INPUT_USD_PER_MILLION,outputRate:env.LM_OUTPUT_USD_PER_MILLION,requestLimit:env.LM_REQUESTS_PER_PERIOD,inputLimit:env.LM_MAX_INPUT_TOKENS,outputLimit:env.LM_MAX_OUTPUT_TOKENS,concurrency:env.LM_MAX_CONCURRENT},budgetFile:env.LM_BUDGET_FILE||path.join(__dirname,'.runtime','usage.json')};
}
function validateRequest(value){
 if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).some(k=>!['receipt','length','mode','purpose'].includes(k)))throw safeError('INVALID_REQUEST','Only a grounded receipt and narration settings may be submitted.',400);
 if(!value.receipt||Object.keys(value.receipt).some(k=>!['id','input','intent','scene','outcome','facts','participant','unresolvedThreads','stateVersion','locale','memory','player','recentDialogue'].includes(k)))throw safeError('INVALID_REQUEST','Narration cannot accept state changes or instructions.',400);
 let receipt;try{receipt=Narrative.makeReceipt(value.receipt)}catch{throw safeError('INVALID_REQUEST','A resolved action receipt is required.',400);}
 if(JSON.stringify(value.receipt).length>18000)throw safeError('TOO_LARGE','The resolved receipt is too large.',413);
 if(!['local','online'].includes(value.mode))throw safeError('MODE_REQUIRED','Choose an explicit local or budgeted online model mode.',400);if(!['complex','expand'].includes(value.purpose))throw safeError('PURPOSE_REQUIRED','Only complex typed scenes or an explicit settled-scene expansion can request a model.',400);
 return {receipt,length:Narrative.LENGTHS.includes(value.length)?value.length:'balanced',mode:value.mode,purpose:value.purpose};
}
function providerBody(payload,config,outputCap=1100){const lengths={brief:'Usually 1 short paragraph, at most 100 words.',balanced:'Usually 1–3 paragraphs, at most 220 words.',detailed:'Use 3–6 paragraphs for a consequential or complex action, at most 420 words; simple questions remain concise.'};return {model:config.model,store:false,stream:true,max_output_tokens:Math.min(outputCap,payload.length==='detailed'?1100:payload.length==='brief'?300:650),instructions:INSTRUCTIONS+'\nLength preference: '+lengths[payload.length],input:[{role:'user',content:[{type:'input_text',text:JSON.stringify({receipt:payload.receipt})}]}]};}
function cacheIdentity(payload,config){return crypto.createHash('sha256').update(JSON.stringify({promptVersion:PROMPT.version,provider:config.provider,model:config.model,endpoint:config.endpoint,payload})).digest('hex');}
async function generate(payload,options){
 const config=options.config,signal=options.signal,emit=options.emit||(()=>{}),request=options.fetch||fetch;
 const started=Date.now();let firstVisibleMs=null,usage=null;const response=await request(config.endpoint,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json',...(config.key?{Authorization:'Bearer '+config.key}:{})},body:JSON.stringify(options.body||providerBody(payload,config)),signal});
 if(!response.ok)throw safeError(response.status===401||response.status===403?'CREDENTIALS_REJECTED':response.status===429?'PROVIDER_LIMIT':'PROVIDER_ERROR',response.status===401||response.status===403?'The provider rejected its server credentials. Use offline narration or correct the server configuration.':'The provider could not complete this narration. The action will not be repeated.');
 if(!response.body||!String(response.headers.get('content-type')).includes('text/event-stream'))throw safeError('INVALID_PROVIDER_RESPONSE','The provider did not return a supported response stream.');
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',data=[],text='',complete=false,bytes=0;
 const event=()=>{if(!data.length)return;const raw=data.join('\n');data=[];if(raw==='[DONE]')return;let item;try{item=JSON.parse(raw)}catch{throw safeError('INVALID_PROVIDER_RESPONSE','The provider stream was malformed.');}
  if(item.type==='response.output_text.delta'){if(complete||typeof item.delta!=='string')throw safeError('INVALID_PROVIDER_RESPONSE','The provider stream was malformed.');if(firstVisibleMs===null)firstVisibleMs=Date.now()-started;text+=item.delta;if(text.length>Narrative.MAX_REPLY)throw safeError('INVALID_PROVIDER_RESPONSE','The provider exceeded its response limit.');emit({type:'delta',text:item.delta});}
  else if(item.type==='response.completed'){if(item.response?.status&&item.response.status!=='completed')throw safeError('PROVIDER_INCOMPLETE','The provider stopped before completing its response.');usage=item.response?.usage||null;complete=true;}
  else if(['error','response.failed','response.incomplete','response.refusal.delta'].includes(item.type))throw safeError('PROVIDER_INCOMPLETE','The provider could not complete this response. Use the preserved offline outcome.');
  else if(item.type==='response.output_item.added'&&['function_call','computer_call','code_interpreter_call'].includes(item.item?.type))throw safeError('INVALID_PROVIDER_RESPONSE','Narration cannot call tools or change game state.');
 };
 try{while(true){const chunk=await reader.read();if(chunk.done)break;bytes+=chunk.value.length;if(bytes>180000)throw safeError('INVALID_PROVIDER_RESPONSE','The provider stream exceeded its size limit.');buffer+=decoder.decode(chunk.value,{stream:true});let at;while((at=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,at).replace(/\r$/,'');buffer=buffer.slice(at+1);if(!line)event();else if(line.startsWith('data:'))data.push(line.slice(5).trimStart());}}
  buffer+=decoder.decode();if(buffer.startsWith('data:'))data.push(buffer.slice(5).trim());event();
 }finally{await reader.cancel().catch(()=>{});}
 if(!complete)throw safeError('PROVIDER_INCOMPLETE','The provider disconnected before completing the response.');
 try{text=Narrative.validateNarration(text,payload.receipt)}catch(error){throw safeError(error.code,'The generated prose did not match the narration contract. Use the preserved offline outcome.');}
 return {type:'done',id:payload.receipt.id,text,provider:config.provider,model:config.model,mode:payload.mode||'online',usage:usage?{input_tokens:usage.input_tokens,output_tokens:usage.output_tokens}:null,diagnostics:{firstVisibleMs,totalMs:Date.now()-started,promptVersion:PROMPT.version,contextBytes:Buffer.byteLength(JSON.stringify(payload.receipt))}};
}
function createServer(options={}){
 const config=options.config||configuration(),root=path.resolve(options.root||path.join(__dirname,'..')),limiter=new Map(),cache=new Map(),inflight=new Set(),now=options.now||Date.now,budget=options.budget||new Budget({...config.budget,file:config.budgetFile||null,now}),encounterArt=options.encounterArt||EncounterArt.createService({config:options.imageConfig||EncounterArt.configuration(),now,fetch:options.imageFetch});
 const publicFiles=new Set(['index.html','sw.js','icon-192.png','icon-512.png','icon.svg']);
 try{for(const match of fs.readFileSync(path.join(root,'index.html'),'utf8').matchAll(/\b(?:src|href)=["']([^"']+)["']/g)){const value=match[1].split(/[?#]/)[0].replace(/^\.\//,'');if(value&&!/^(?:[a-z]+:|\/|#)/i.test(value)&&!value.includes('..'))publicFiles.add(value);}}catch{}
 const publicPath=relative=>!relative.split(/[\\/]/).some(p=>p.startsWith('.'))&&!relative.includes('\\')&&(publicFiles.has(relative)||/^(?:art|audio|icons)\/.+\.(?:webp|png|jpe?g|svg|m4a|mp3|wav|ogg|woff2?)$/.test(relative));
 const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(value));};
 const sameOrigin=req=>{let expected;try{if(config.origin){const url=new URL(config.origin);if(url.origin!==config.origin||!['http:','https:'].includes(url.protocol))return false;expected=url.origin;}else{const url=new URL('http://'+req.headers.host);if(url.username||url.password||!['127.0.0.1','localhost','[::1]'].includes(url.hostname)||Number(url.port||80)!==req.socket.localPort)return false;expected=url.origin;}}catch{return false;}if(!req.headers.origin)return !['cross-site','same-site'].includes(req.headers['sec-fetch-site']);return req.headers.origin===expected;};
 const server=http.createServer(async(req,res)=>{
  res.setHeader('X-Content-Type-Options','nosniff');let pathname;try{pathname=new URL(req.url,'http://localhost').pathname}catch{return json(res,400,{code:'INVALID_URL'});}
  if(pathname==='/api/encounter-art/status'&&req.method==='GET'){try{return json(res,200,encounterArt.status());}catch{return json(res,503,{code:'ART_BUDGET_INVALID',message:'The image budget ledger is unavailable. Image generation is disabled; local artwork remains active.'});}}
  if(pathname.startsWith('/api/encounter-art/cache/')){
   if(!['GET','HEAD'].includes(req.method))return json(res,405,{code:'METHOD_NOT_ALLOWED'});if(!sameOrigin(req))return json(res,403,{code:'ORIGIN_REJECTED'});const match=/^\/api\/encounter-art\/cache\/([a-f0-9]{64})\.png$/.exec(pathname);if(!match)return json(res,404,{code:'ART_NOT_FOUND'});
   try{const bytes=encounterArt.read(match[1]);res.writeHead(200,{'Content-Type':'image/png','Content-Length':bytes.length,'Cache-Control':'private, max-age=31536000, immutable','Cross-Origin-Resource-Policy':'same-origin'});return res.end(req.method==='HEAD'?undefined:bytes);}catch{return json(res,404,{code:'ART_NOT_FOUND',message:'The cached portrait is unavailable. Local artwork remains active.'});}
  }
  if(pathname==='/api/encounter-art'){
   if(req.method!=='POST')return json(res,405,{code:'METHOD_NOT_ALLOWED'});if(!sameOrigin(req))return json(res,403,{code:'ORIGIN_REJECTED'});if(String(req.headers['content-type']).split(';')[0].trim()!=='application/json')return json(res,415,{code:'JSON_REQUIRED'});
   const rateKey='art|'+req.socket.remoteAddress,rate=limiter.get(rateKey)||{at:now(),count:0};if(now()-rate.at>60000){rate.at=now();rate.count=0;}rate.count++;limiter.set(rateKey,rate);if(limiter.size>512)limiter.delete(limiter.keys().next().value);if(rate.count>6)return json(res,429,{code:'ART_RATE_LIMITED',message:'Too many portrait requests. Local artwork remains active.'});
   const controller=new AbortController();res.on('close',()=>{if(!res.writableEnded)controller.abort('disconnected');});try{const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>4096)return json(res,413,{code:'ART_TOO_LARGE'});chunks.push(chunk);}let value;try{value=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{return json(res,400,{code:'INVALID_JSON'});}const result=await encounterArt.request(value,{signal:controller.signal});if(!res.destroyed)return json(res,200,result);
   }catch(e){if(!res.destroyed)return json(res,e.public?e.status||502:502,{code:e.public?e.code:'ART_UNAVAILABLE',message:e.public?e.message:'The optional artwork service is unavailable. Local artwork remains active.'});}return;
  }
  if(pathname==='/api/narrator-status'&&req.method==='GET'){try{const usage=budget.status();return json(res,200,{ready:!!config.ready&&usage.enabled,mode:'offline by default',provider:config.provider||null,model:config.model||null,promptVersion:PROMPT.version,modes:{offline:{ready:true},local:{ready:!!config.local?.ready,model:config.local?.model||null},online:{configured:!!config.ready,ready:!!config.ready&&usage.enabled&&usage.remainingUsd>0}},budget:usage});}catch{return json(res,503,{code:'BUDGET_INVALID',message:'The budget ledger is unavailable; hosted calls are disabled.'});}}
  if(pathname==='/api/narrator-test'){
   if(req.method!=='POST'||!sameOrigin(req))return json(res,403,{code:'ORIGIN_REJECTED'});const testKey='test|'+req.socket.remoteAddress,testRate=limiter.get(testKey)||{at:now(),count:0};if(now()-testRate.at>60000){testRate.at=now();testRate.count=0;}testRate.count++;limiter.set(testKey,testRate);if(limiter.size>512)limiter.delete(limiter.keys().next().value);if(testRate.count>8)return json(res,429,{code:'RATE_LIMITED'});let raw='',size=0;try{for await(const chunk of req){size+=chunk.length;if(size>200)return json(res,413,{code:'TOO_LARGE'});raw+=chunk.toString();}}catch{if(!res.destroyed)return json(res,400,{code:'REQUEST_INTERRUPTED'});return;}let mode;try{mode=JSON.parse(raw).mode}catch{return json(res,400,{code:'INVALID_JSON'})}if(!['local','online'].includes(mode))return json(res,400,{code:'MODE_REQUIRED'});const chosen=mode==='local'?config.local:config;if(!chosen?.ready||!endpointValid(chosen.endpoint,mode==='local'))return json(res,503,{code:'NOT_CONFIGURED',message:'No valid endpoint and model have been configured for this mode.'});const control=new AbortController(),timer=setTimeout(()=>control.abort(),5000);
   try{const url=new URL(chosen.endpoint);url.pathname=url.pathname.replace(/\/responses\/?$/,'/models/'+encodeURIComponent(chosen.model));const response=await (options.fetch||fetch)(url.href,{method:'GET',redirect:'error',headers:chosen.key?{Authorization:'Bearer '+chosen.key}:{},signal:control.signal});return json(res,response.ok?200:502,{ok:response.ok,code:response.ok?'CONNECTED':'CONNECTION_REJECTED',message:response.ok?'Model metadata endpoint responded. No generation was requested.':'The model metadata endpoint rejected this test; no generation was requested.',mode,model:chosen.model,generationRequests:0});}catch{return json(res,502,{code:'CONNECTION_FAILED',message:'Connection test failed. No generation was requested.'})}finally{clearTimeout(timer)}
  }
  if(pathname==='/api/narrate'){
   if(req.method!=='POST')return json(res,405,{code:'METHOD_NOT_ALLOWED'});
   if(!sameOrigin(req))return json(res,403,{code:'ORIGIN_REJECTED'});
   if(String(req.headers['content-type']).split(';')[0].trim()!=='application/json')return json(res,415,{code:'JSON_REQUIRED'});
   const ip=req.socket.remoteAddress||'unknown',time=now();let rate=limiter.get(ip)||{at:time,count:0};if(time-rate.at>60000)rate={at:time,count:0};rate.count++;limiter.set(ip,rate);if(limiter.size>512)limiter.delete(limiter.keys().next().value);if(rate.count>16)return json(res,429,{code:'RATE_LIMITED'});
   let chunks=[],size=0,payload,key,fingerprint,controller,timer,ownsFlight=false,reservation=null,chosen;
   try{
    for await(const chunk of req){size+=chunk.length;if(size>24000)throw safeError('TOO_LARGE','The narration request is too large.',413);chunks.push(chunk);}
    let value;try{value=JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw safeError('INVALID_JSON','The request was not valid JSON.',400);}payload=validateRequest(value);chosen=payload.mode==='local'?config.local:config;if(!chosen?.ready||!endpointValid(chosen.endpoint,payload.mode==='local'))throw safeError('NOT_CONFIGURED','The selected model mode is not configured with a valid endpoint.',503);
    const intent=Narrative.interpret(payload.receipt.input,{currentNpc:payload.receipt.participant?.id,participants:payload.receipt.participant?[payload.receipt.participant]:[]});if(!Narrative.shouldNarrate(payload.receipt.input,intent,{mode:payload.mode,expand:payload.purpose==='expand'}))throw safeError('LOCAL_ACTION','This routine interaction uses local narration. No model request was dispatched.',400);
    key=ip+'|'+payload.receipt.id;fingerprint=cacheIdentity(payload,chosen);
    const prior=cache.get(key);if(prior&&time-prior.at<900000){if(prior.fingerprint!==fingerprint)throw safeError('ID_CONFLICT','This action ID has already been used with different content.',409);res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store'});res.write(JSON.stringify({type:'delta',text:prior.result.text})+'\n');return res.end(JSON.stringify(prior.result)+'\n');}
    if(inflight.has(key))throw safeError('ALREADY_PENDING','This action already has narration in progress.',409);
    const requestBody=providerBody(payload,chosen,budget.config.outputLimit),estimate=Buffer.byteLength(requestBody.instructions)+Buffer.byteLength(JSON.stringify(requestBody.input))+1024;
    if(estimate>budget.config.inputLimit)throw safeError('TOKEN_LIMIT','This scene exceeds the configured input token bound; use the offline outcome.',413);
    if(payload.mode==='online'){reservation=budget.reserve({key:fingerprint,identity:payload.receipt.id,inputTokens:estimate,outputTokens:requestBody.max_output_tokens,ttlMs:config.timeoutMs+10000});if(reservation.cached){res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store'});res.write(JSON.stringify({type:'delta',text:reservation.cached.text})+'\n');return res.end(JSON.stringify({...reservation.cached,diagnostics:{...reservation.cached.diagnostics,cacheHit:true}})+'\n');}}else if(inflight.size>=budget.config.concurrency)throw safeError('CONCURRENCY_LIMIT','The local narrator is busy. No new inference was started.',429);
    inflight.add(key);ownsFlight=true;controller=new AbortController();timer=setTimeout(()=>controller.abort('timeout'),config.timeoutMs);res.on('close',()=>{if(!res.writableEnded)controller.abort('disconnected');});
    res.writeHead(200,{'Content-Type':'application/x-ndjson','Cache-Control':'no-store','X-Accel-Buffering':'no'});res.write(JSON.stringify({type:'status',stage:'narrating'})+'\n');
    const result=await generate(payload,{config:chosen,body:requestBody,signal:controller.signal,fetch:options.fetch,emit:x=>{if(!res.destroyed)res.write(JSON.stringify(x)+'\n');}});if(payload.mode==='online'){const cost=budget.complete(fingerprint,result,result.usage);result.diagnostics={...result.diagnostics,...cost,inputTokenBound:estimate,outputTokenLimit:requestBody.max_output_tokens};reservation=null;}else result.diagnostics={...result.diagnostics,estimatedUsd:0,hostedRequests:0};
    cache.set(key,{at:now(),fingerprint,result});while(cache.size>128)cache.delete(cache.keys().next().value);if(!res.destroyed)res.end(JSON.stringify(result)+'\n');
   }catch(error){if(reservation&&!reservation.cached){try{budget.uncertain(fingerprint)}catch{}}const code=controller?.signal.aborted?'TIMEOUT':error.public?error.code:'PROVIDER_UNAVAILABLE',message=controller?.signal.aborted?'Narration was interrupted. The resolved action remains safe; any dispatched cost reservation is retained.':error.public?error.message:'The narration service is unavailable. The resolved action remains safe.';
    if(!res.destroyed){if(res.headersSent)res.end(JSON.stringify({type:'error',code,message})+'\n');else json(res,error.status||502,{code,message});}
   }finally{clearTimeout(timer);if(ownsFlight)inflight.delete(key);}
   return;
  }
  if(req.method!=='GET'&&req.method!=='HEAD')return json(res,405,{code:'METHOD_NOT_ALLOWED'});
  // Only entry-point dependencies and public media are served, including after symlink resolution.
  let relative;try{relative=decodeURIComponent(pathname)}catch{return json(res,400,{code:'INVALID_URL'});}
  relative=relative==='/'?'index.html':relative.replace(/^\//,'');if(!publicPath(relative))return json(res,404,{code:'NOT_FOUND'});
  let file=path.resolve(root,relative);if(!file.startsWith(root+path.sep))return json(res,404,{code:'NOT_FOUND'});if(config.budgetFile&&file.toLowerCase()===path.resolve(config.budgetFile).toLowerCase())return json(res,404,{code:'NOT_FOUND'});
  const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.wav':'audio/wav','.mp3':'audio/mpeg','.m4a':'audio/mp4','.ogg':'audio/ogg','.woff':'font/woff','.woff2':'font/woff2','.json':'application/json','.webmanifest':'application/manifest+json'};
  if(!types[path.extname(file)])return json(res,404,{code:'NOT_FOUND'});
  try{const actual=await fs.promises.realpath(file);if(!actual.startsWith(root+path.sep)||!publicPath(path.relative(root,actual).replace(/\\/g,'/')))return json(res,404,{code:'NOT_FOUND'});const stat=await fs.promises.stat(actual);if(!stat.isFile())return json(res,404,{code:'NOT_FOUND'});let start=0,end=stat.size-1,status=200;
   if(req.headers.range){const match=/^bytes=(\d*)-(\d*)$/.exec(req.headers.range),a=match?.[1]?Number(match[1]):null,b=match?.[2]?Number(match[2]):null;let valid=!!match&&stat.size>0&&(a!==null||b!==null)&&(a===null||Number.isSafeInteger(a))&&(b===null||Number.isSafeInteger(b));if(valid){if(a===null){valid=b>0;start=Math.max(0,stat.size-b);}else{start=a;end=b===null?end:Math.min(b,end);valid=start<stat.size&&end>=start;}}if(!valid){res.setHeader('Content-Range','bytes */'+stat.size);return json(res,416,{code:'INVALID_RANGE'});}status=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${stat.size}`);}
   res.writeHead(status,{'Content-Type':types[path.extname(file)],'Content-Length':Math.max(0,end-start+1),'Accept-Ranges':'bytes','Cache-Control':/\.(?:js|css|html|webmanifest)$/.test(file)?'no-cache':'public, max-age=3600'});if(req.method==='HEAD'||stat.size===0)res.end();else fs.createReadStream(actual,{start,end}).pipe(res);
  }catch{return json(res,404,{code:'NOT_FOUND'});}
 });
 server.requestTimeout=20000;server.headersTimeout=10000;server.keepAliveTimeout=5000;return server;
}
if(require.main===module){const config=configuration(),port=Number(process.env.PORT)||4177;createServer({config}).listen(port,'127.0.0.1',()=>console.log(`Living Murim at http://127.0.0.1:${port} — ${config.ready?'connected narrator configured: '+config.provider+'/'+config.model:'offline; narrator is not configured'}`));}
module.exports={configuration,validateRequest,generate,providerBody,cacheIdentity,createServer,INSTRUCTIONS,PROMPT};
